bipedal-locomotion-framework: BipedalLocomotion::TSID::JointsDynamicsTask Class Reference
BipedalLocomotion::TSID::JointsDynamicsTask Class Reference
JointsDynamicsTask is a concrete implementation of the Task.
#include <BipedalLocomotion/TSID/JointsDynamicsTask.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler, const System::VariablesHandler &variablesHandler) override
Initialize the planner.
bool update () override
Update the content of the element.
Public Member Functions inherited from BipedalLocomotion::TSID::Task
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the element.
Additional Inherited Members
Protected Member Functions inherited from BipedalLocomotion::TSID::Task
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::TSID::Task
Eigen::MatrixXd m_A
Element Matrix.
Eigen::VectorXd m_b
Element Vector.
std::string m_description {"Generic Optimal Control Element"}
String describing the content of the element.
std::shared_ptr< iDynTree::KinDynComputations > m_kinDyn
Pointer to a KinDynComputations object.
Detailed Description
JointsDynamicsTask is a concrete implementation of the Task.
Please use this element if you want to consider the joints dynamics only. The task represents the following equation
\[ M_{s}(q) \dot{\nu} + h_{s}(q,\nu) = \sum J_k^\top f_k + \tau \]
where the suffix \(s\) indicates the last n rows of the vector/matrix. \(J_k\) is the robot jacobian associated to the contact wrench \(d_k\). \(\tau\) are the joints torque.
Note
Please consider that here the MIXED representation is used to define the 6d-velocity and 6d-forces. You can find further details in Section 2.3.4 of https://traversaro.github.io/phd-thesis/traversaro-phd-thesis.pdf.
Definition at line 31 of file JointsDynamicsTask.h.
Member Function Documentation
initialize()
bool JointsDynamicsTask::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler, const System::VariablesHandler & variablesHandler) override virtual
Initialize the planner.
Parameters
paramHandler pointer to the parameters handler.
variablesHandler reference to a variables handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_acceleration_variable_name string Name of the variable contained in VariablesHandler describing the robot acceleration Yes
joint_torques_variable_name string Name of the variable contained in VariablesHandler describing the joints torque Yes
max_number_of_contacts int Maximum number of contacts. The default value is 0. No
CONTACT_<i> group i is an int between 0 and max_number_of_contacts The group must contain variable_name and frame_name Yes
variable_name string Name of the variable contained in VariablesHandler describing the contact Yes
frame_name string Name of the frame associated to the contact Yes
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::TSID::Task.
Definition at line 17 of file JointsDynamicsTask.cpp.
References std::endl(), BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), std::weak_ptr< T >::lock(), and std::to_string().
update()
bool JointsDynamicsTask::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::TSID::Task.
Definition at line 146 of file JointsDynamicsTask.cpp.
References std::endl().
The documentation for this class was generated from the following files:
TSID/include/BipedalLocomotion/TSID/JointsDynamicsTask.h
TSID/src/JointsDynamicsTask.cpp