bipedal-locomotion-framework: BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived > Class Template Reference
BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived > Class Template Reference abstract
Fixed step integrator base class.
#include <BipedalLocomotion/System/FixedStepIntegrator.h>
Public Member Functions
FixedStepIntegrator (const double &dT)
Constructor.
bool integrate (double initialTime, double finalTime) final
Integrate the dynamical system from initialTime to finalTime.
Public Member Functions inherited from BipedalLocomotion::System::Integrator< DynamicalSystemDerived >
bool setDynamicalSystem (std::shared_ptr< DynamicalSystemDerived > dynamicalSystem)
Set the DynamicalSystem to be considered.
const std::weak_ptr< DynamicalSystemDerived > dynamicalSystem () const
Get the dynamical system.
const DynamicalSystemDerived::StateType & getSolution () const
Retrieve the solution.
Protected Member Functions
virtual bool oneStepIntegration (double t0, double dT)=0
Integrate one step.
Protected Attributes
double m_dT {0.0}
Fixed step size.
Protected Attributes inherited from BipedalLocomotion::System::Integrator< DynamicalSystemDerived >
std::shared_ptr< DynamicalSystemDerived > m_dynamicalSystem
Pointer to a dynamical system.
Detailed Description
template<typename DynamicalSystemDerived>
class BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived >
Fixed step integrator base class.
Please inherit publicly from this class in order to specify a custom integration method.
Template Parameters
DynamicalSystemDerived a class derived from DynamicalSystem
Definition at line 27 of file FixedStepIntegrator.h.
Constructor & Destructor Documentation
FixedStepIntegrator()
template<typename DynamicalSystemDerived > BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived >::FixedStepIntegrator (const double & dT) inline
Constructor.
Parameters
dT the sampling time
Definition at line 47 of file FixedStepIntegrator.h.
References BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived >::integrate().
Member Function Documentation
integrate()
template<typename DynamicalSystemDerived > bool BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived >::integrate (double initialTime, double finalTime) final virtual
Integrate the dynamical system from initialTime to finalTime.
Note
We assume a constant control input in the interval.
Parameters
initialTime initial time of the integration.
finalTime final time of the integration.
Returns
true in case of success, false otherwise.
Implements BipedalLocomotion::System::Integrator< DynamicalSystemDerived >.
Definition at line 22 of file FixedStepIntegrator.tpp.
References std::ceil(), and std::endl().
Referenced by BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived >::FixedStepIntegrator().
oneStepIntegration()
template<typename DynamicalSystemDerived > virtual bool BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived >::oneStepIntegration (double t0, double dT) protected pure virtual
Integrate one step.
Parameters
t0 initial time.
dT sampling time.
Returns
true in case of success, false otherwise.
Field Documentation
m_dT
template<typename DynamicalSystemDerived > double BipedalLocomotion::System::FixedStepIntegrator< DynamicalSystemDerived >::m_dT {0.0} protected
Fixed step size.
Definition at line 31 of file FixedStepIntegrator.h.
The documentation for this class was generated from the following files:
System/include/BipedalLocomotion/System/FixedStepIntegrator.h
System/include/BipedalLocomotion/System/FixedStepIntegrator.tpp