bipedal-locomotion-framework: BipedalLocomotion::TSID::JointsTrackingTask Class Reference
BipedalLocomotion::TSID::JointsTrackingTask Class Reference
JointsTrackingTask is a concrete implementation of the Task.
#include <BipedalLocomotion/TSID/JointsTrackingTask.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler, const System::VariablesHandler &variablesHandler) override
Initialize the planner.
bool update () override
Update the content of the element.
bool setSetpoint (Eigen::Ref< const Eigen::VectorXd > jointPosition)
Set the desired setpoint.
bool setSetpoint (Eigen::Ref< const Eigen::VectorXd > jointPosition, Eigen::Ref< const Eigen::VectorXd > jointVelocity)
Set the desired setpoint.
bool setSetpoint (Eigen::Ref< const Eigen::VectorXd > jointPosition, Eigen::Ref< const Eigen::VectorXd > jointVelocity, Eigen::Ref< const Eigen::VectorXd > jointAcceleration)
Set the desired setpoint.
Public Member Functions inherited from BipedalLocomotion::TSID::Task
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the element.
Additional Inherited Members
Protected Member Functions inherited from BipedalLocomotion::TSID::Task
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::TSID::Task
Eigen::MatrixXd m_A
Element Matrix.
Eigen::VectorXd m_b
Element Vector.
std::string m_description {"Generic Optimal Control Element"}
String describing the content of the element.
std::shared_ptr< iDynTree::KinDynComputations > m_kinDyn
Pointer to a KinDynComputations object.
Detailed Description
JointsTrackingTask is a concrete implementation of the Task.
Please use this element if you want to control the desired joint position of the robot. The task represents the following equation
\[ \begin{bmatrix} 0_6 & I_n \end{bmatrix} \nu = \ddot{s} ^ * \]
where \(0_6\) and \(I_n\) are the zero and the identity matrix. The desired joint acceleration is chosen such that the joint will converge to the desired trajectory and it is computed with a standard standard PD controller in \(\mathbb{R}^n\).
Definition at line 31 of file JointsTrackingTask.h.
Member Function Documentation
initialize()
bool JointsTrackingTask::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler, const System::VariablesHandler & variablesHandler) override virtual
Initialize the planner.
Parameters
paramHandler pointer to the parameters handler.
variablesHandler reference to a variables handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_acceleration_variable_name string Name of the variable contained in VariablesHandler describing the robot acceleration Yes
kp vector Proportional controller gain Yes
kd vector Derivative Gain of the controller. if not specified \(k_d = 2 \sqrt{k_p}\) No
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::TSID::Task.
Definition at line 15 of file JointsTrackingTask.cpp.
References std::endl(), BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), and std::weak_ptr< T >::lock().
setSetpoint() [1/3]
bool JointsTrackingTask::setSetpoint (Eigen::Ref< const Eigen::VectorXd > jointPosition)
Set the desired setpoint.
Parameters
jointPosition vector containing the desired joint position in radians.
Note
The desired velocity and acceleration are implicitly set to zero.
Returns
True in case of success, false otherwise.
Definition at line 116 of file JointsTrackingTask.cpp.
setSetpoint() [2/3]
bool JointsTrackingTask::setSetpoint (Eigen::Ref< const Eigen::VectorXd > jointPosition, Eigen::Ref< const Eigen::VectorXd > jointVelocity)
Set the desired setpoint.
Parameters
jointPosition vector containing the desired joint position in radians.
jointVelocity vector containing the desired joint velocity in radians per second.
Note
The desired acceleration is implicitly set to zero.
Returns
True in case of success, false otherwise.
Definition at line 121 of file JointsTrackingTask.cpp.
setSetpoint() [3/3]
bool JointsTrackingTask::setSetpoint (Eigen::Ref< const Eigen::VectorXd > jointPosition, Eigen::Ref< const Eigen::VectorXd > jointVelocity, Eigen::Ref< const Eigen::VectorXd > jointAcceleration)
Set the desired setpoint.
Parameters
jointPosition vector containing the desired joint position in radians.
jointVelocity vector containing the desired joint velocity in radians per second.
jointAcceleration vector containing the desired joint velocity in radians per second square.
Returns
True in case of success, false otherwise.
Definition at line 127 of file JointsTrackingTask.cpp.
References std::endl().
update()
bool JointsTrackingTask::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::TSID::Task.
Definition at line 93 of file JointsTrackingTask.cpp.
References std::endl().
The documentation for this class was generated from the following files:
TSID/include/BipedalLocomotion/TSID/JointsTrackingTask.h
TSID/src/JointsTrackingTask.cpp