bipedal-locomotion-framework: BipedalLocomotion::Planners::SwingFootPlanner Class Reference
BipedalLocomotion::Planners::SwingFootPlanner Class Reference
SwingFootPlanner implement a minimum jerk trajectory planner for the swing foot.
#include <BipedalLocomotion/Planners/SwingFootPlanner.h>
Public Member Functions
bool initialize (std::shared_ptr< ParametersHandler::IParametersHandler > handler)
Initialize the planner.
void setContactList (const ContactList &contactList)
Set the contact list.
const SwingFootPlannerState & get () const final
Get the object.
bool isValid () const final
Determines the validity of the object retrieved with get()
bool advance () final
Advance the internal state.
Detailed Description
SwingFootPlanner implement a minimum jerk trajectory planner for the swing foot.
The planner is designed in SE(3) and we assume that initial 6d-acceleration and 6d-velocity of the foot is always equal to zero at take off. The trajectory of the foot will belong to the Geodesic.
Definition at line 42 of file SwingFootPlanner.h.
Member Function Documentation
advance()
bool SwingFootPlanner::advance () final virtual
Advance the internal state.
This may change the value retrievable from get().
Returns
True if the advance is successfull.
Implements BipedalLocomotion::System::Advanceable< SwingFootPlannerState >.
Definition at line 161 of file SwingFootPlanner.cpp.
References std::advance(), BipedalLocomotion::Planners::ContactList::end(), std::endl(), BipedalLocomotion::Planners::ContactList::lastContact(), std::min(), BipedalLocomotion::Planners::SwingFootPlannerState::mixedAcceleration, BipedalLocomotion::Planners::SwingFootPlannerState::mixedVelocity, std::next(), BipedalLocomotion::Planners::QuinticSpline::setKnots(), BipedalLocomotion::Planners::SO3Planner< trivialization >::setRotations(), and BipedalLocomotion::Planners::SwingFootPlannerState::transform.
get()
const SwingFootPlannerState & SwingFootPlanner::get () const final virtual
Get the object.
Returns
a const reference of the requested object.
Implements BipedalLocomotion::System::Advanceable< SwingFootPlannerState >.
Definition at line 102 of file SwingFootPlanner.cpp.
References std::endl(), BipedalLocomotion::Planners::SO3Planner< trivialization >::evaluatePoint(), BipedalLocomotion::Planners::QuinticSpline::evaluatePoint(), BipedalLocomotion::Planners::SwingFootPlannerState::mixedAcceleration, BipedalLocomotion::Planners::SwingFootPlannerState::mixedVelocity, and BipedalLocomotion::Planners::SwingFootPlannerState::transform.
initialize()
bool SwingFootPlanner::initialize (std::shared_ptr< ParametersHandler::IParametersHandler > handler)
Initialize the planner.
Parameters
handler pointer to the parameter handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
sampling_time double Sampling time of the planner in seconds Yes
step_height double Height of the swing foot. It is not the maximum height of the foot. If apex time is 0.5 step_height is the maximum Yes
foot_apex_time double Number between 0 and 1 representing the foot apex instant. If 0 the apex happens at take off if 1 at touch down Yes
foot_landing_velocity double Landing vertical velocity Yes
foot_landing_acceleration double Landing vertical acceleration Yes
Returns
True in case of success/false otherwise.
Definition at line 15 of file SwingFootPlanner.cpp.
References std::endl(), BipedalLocomotion::Planners::QuinticSpline::setFinalConditions(), and BipedalLocomotion::Planners::QuinticSpline::setInitialConditions().
isValid()
bool SwingFootPlanner::isValid () const final virtual
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Implements BipedalLocomotion::System::Advanceable< SwingFootPlannerState >.
Definition at line 97 of file SwingFootPlanner.cpp.
References BipedalLocomotion::Planners::ContactList::size().
setContactList()
void SwingFootPlanner::setContactList (const ContactList & contactList)
Set the contact list.
Parameters
contactList contains the list fora given contact
Definition at line 81 of file SwingFootPlanner.cpp.
References BipedalLocomotion::Planners::ContactList::firstContact(), BipedalLocomotion::Planners::SwingFootPlannerState::mixedAcceleration, BipedalLocomotion::Planners::SwingFootPlannerState::mixedVelocity, and BipedalLocomotion::Planners::SwingFootPlannerState::transform.
The documentation for this class was generated from the following files:
Planners/include/BipedalLocomotion/Planners/SwingFootPlanner.h
Planners/src/SwingFootPlanner.cpp