bipedal-locomotion-framework: BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations Class Reference
BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations Class Reference
iDynTree based model-specific computations class This is class is used in a required configuration step for the estimator All the model related kinematics and dynamics computations specific to the floating base estimator are contained within this class.
#include <BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h>
Public Member Functions
bool setModel (const iDynTree::Model &model)
Set the reduced model.
bool setBaseLinkAndIMU (const std::string &baseLinkFrame, const std::string &imuFrame)
Set base link name and name of the IMU rigidly attached to the IMU.
bool setFeetContactFrames (const std::string &lFootContactFrame, const std::string &rFootContactFrame)
Set the feet contact frames, expected to be in contact with the environment.
bool isModelInfoLoaded ()
Check if model is configured with the required information.
bool getIMU_H_feet (const iDynTree::JointPosDoubleArray &encoders, iDynTree::Transform &IMU_H_l_foot, iDynTree::Transform &IMU_H_r_foot)
Get relative pose between IMU and the feet.
bool getIMU_H_feet (const iDynTree::JointPosDoubleArray &encoders, iDynTree::Transform &IMU_H_l_foot, iDynTree::Transform &IMU_H_r_foot, iDynTree::MatrixDynSize &J_IMULF, iDynTree::MatrixDynSize &J_IMURF)
Get relative pose between IMU and the feet.
bool getBaseStateFromIMUState (const iDynTree::Transform &A_H_IMU, const iDynTree::Twist &v_IMU, iDynTree::Transform &A_H_B, iDynTree::Twist &v_B)
Get the base link pose and velocity from the estimated IMU pose and velocity.
const int & nrJoints () const
Getters.
const std::string & baseLink () const
const std::string & baseLinkIMU () const
const std::string & leftFootContactFrame () const
const std::string & rightFootContactFrame () const
const iDynTree::Transform & base_H_IMU () const
const bool & isModelSet () const
Detailed Description
iDynTree based model-specific computations class This is class is used in a required configuration step for the estimator All the model related kinematics and dynamics computations specific to the floating base estimator are contained within this class.
Definition at line 43 of file FloatingBaseEstimator.h.
Member Function Documentation
getBaseStateFromIMUState()
bool FloatingBaseEstimator::ModelComputations::getBaseStateFromIMUState (const iDynTree::Transform & A_H_IMU, const iDynTree::Twist & v_IMU, iDynTree::Transform & A_H_B, iDynTree::Twist & v_B)
Get the base link pose and velocity from the estimated IMU pose and velocity.
Note
the input and output velocities are both specified in mixed-velocity representation
Parameters
[in] A_H_IMU pose of the IMU in the world
[in] v_IMU mixed-trivialized velocity of the IMU in the world
[out] A_H_B pose of the base link in the world
[out] v_B mixed-trivialized velocity of the base link in the world
Returns
True in case of success, false otherwise.
Definition at line 208 of file FloatingBaseEstimator.cpp.
References std::endl().
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::setupPriorDevs().
getIMU_H_feet() [1/2]
bool FloatingBaseEstimator::ModelComputations::getIMU_H_feet (const iDynTree::JointPosDoubleArray & encoders, iDynTree::Transform & IMU_H_l_foot, iDynTree::Transform & IMU_H_r_foot)
Get relative pose between IMU and the feet.
Parameters
[in] encoders joint positions through encoder measurements
[out] IMU_H_l_foot pose of the left foot contact frame with respect to the IMU frame
[out] IMU_H_r_foot pose of the right foot contact frame with respect to the IMU frame
Returns
True in case of success, false otherwise.
Definition at line 230 of file FloatingBaseEstimator.cpp.
References std::endl().
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), BipedalLocomotion::Estimators::FloatingBaseEstimator::resetEstimator(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
getIMU_H_feet() [2/2]
bool FloatingBaseEstimator::ModelComputations::getIMU_H_feet (const iDynTree::JointPosDoubleArray & encoders, iDynTree::Transform & IMU_H_l_foot, iDynTree::Transform & IMU_H_r_foot, iDynTree::MatrixDynSize & J_IMULF, iDynTree::MatrixDynSize & J_IMURF)
Get relative pose between IMU and the feet.
Parameters
[in] encoders joint positions through encoder measurements
[out] IMU_H_l_foot pose of the left foot contact frame with respect to the IMU frame
[out] IMU_H_r_foot pose of the right foot contact frame with respect to the IMU frame
[out] J_IMULF Jacobian of left foot frame with respect to IMU frame in mixed-velocity trivialization
[out] J_IMURF Jacobian of right foot frame with respect to IMU frame in mixed-velocity trivialization
Returns
True in case of success, false otherwise.
Definition at line 252 of file FloatingBaseEstimator.cpp.
isModelInfoLoaded()
bool FloatingBaseEstimator::ModelComputations::isModelInfoLoaded ()
Check if model is configured with the required information.
Returns
True in case of success, false otherwise.
Definition at line 198 of file FloatingBaseEstimator.cpp.
nrJoints()
const int& BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints () const inline
Getters.
Definition at line 116 of file FloatingBaseEstimator.h.
References BipedalLocomotion::Estimators::FloatingBaseEstimator::advance(), BipedalLocomotion::Estimators::FloatingBaseEstimator::initialize(), BipedalLocomotion::Estimators::FloatingBaseEstimator::resetEstimator(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setContacts(), BipedalLocomotion::Estimators::FloatingBaseEstimator::setIMUMeasurement(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::setKinematics().
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::setKinematics(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::setupSensorDevs().
setBaseLinkAndIMU()
bool FloatingBaseEstimator::ModelComputations::setBaseLinkAndIMU (const std::string & baseLinkFrame, const std::string & imuFrame)
Set base link name and name of the IMU rigidly attached to the IMU.
Parameters
[in] baseLinkFrame name of the base link frame
[in] imuFrame name of the IMU frame
Returns
True in case of success, false otherwise.
Definition at line 133 of file FloatingBaseEstimator.cpp.
References std::endl().
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::get().
setFeetContactFrames()
bool FloatingBaseEstimator::ModelComputations::setFeetContactFrames (const std::string & lFootContactFrame, const std::string & rFootContactFrame)
Set the feet contact frames, expected to be in contact with the environment.
Parameters
[in] lFootContactFrame left foot contact frame
[in] rFootContactFrame right foot contact frame
Returns
True in case of success, false otherwise.
Definition at line 173 of file FloatingBaseEstimator.cpp.
References std::endl().
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::get().
setModel()
bool FloatingBaseEstimator::ModelComputations::setModel (const iDynTree::Model & model)
Set the reduced model.
Parameters
[in] model reduced iDynTree model
Returns
True in case of success, false otherwise.
Definition at line 121 of file FloatingBaseEstimator.cpp.
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::initialize().
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
Estimators/src/FloatingBaseEstimator.cpp