bipedal-locomotion-framework: BipedalLocomotion::Estimators::ContactDetector Class Reference
BipedalLocomotion::Estimators::ContactDetector Class Reference
Public Member Functions
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configure generic parameters.
virtual bool advance () final
Compute one step of the detector The derived class must implement its own methods for setting measurements and update states to be called within the advance() method.
virtual bool resetContacts () final
Reset the internal contact states of the detector to false.
virtual const EstimatedContactList & get () const final
Get contact states.
bool get (const std::string &contactName, BipedalLocomotion::Contacts::EstimatedContact &contact) const
Get state of specific contact.
BipedalLocomotion::Contacts::EstimatedContact get (const std::string &contactName) const
Get state of specific contact.
virtual bool isValid () const final
Determines the validity of the object retrieved with get()
Protected Types
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Member Functions
virtual bool customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
These custom parameter specifications should be specified by the derived class.
virtual bool updateContactStates ()
The derived class must implement the contact detection technique to update the contact states.
Protected Attributes
State m_detectorState {State::NotInitialized}
State of the estimator.
EstimatedContactList m_contactStates
Detailed Description
Definition at line 25 of file ContactDetector.h.
Member Enumeration Documentation
State
enum BipedalLocomotion::Estimators::ContactDetector::State strong protected
Enumerator used to determine the running state of the estimator.
Enumerator
NotInitialized
The estimator is not initialized yet call FloatingBaseEstimator::initialze method to initialize it.
Initialized
The estimator is initialized and ready to be used.
Running
The estimator is running.
Definition at line 97 of file ContactDetector.h.
Member Function Documentation
advance()
bool ContactDetector::advance () final virtual
Compute one step of the detector The derived class must implement its own methods for setting measurements and update states to be called within the advance() method.
Returns
True in case of success, false otherwise.
Implements BipedalLocomotion::System::Advanceable< EstimatedContactList >.
Definition at line 53 of file ContactDetector.cpp.
References std::endl().
customInitialization()
bool ContactDetector::customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected virtual
These custom parameter specifications should be specified by the derived class.
Parameters
[in] handler configure the custom parameters for the estimator
Returns
True if success, false otherwise
Reimplemented in BipedalLocomotion::Estimators::SchmittTriggerDetector.
Definition at line 48 of file ContactDetector.cpp.
get() [1/3]
const EstimatedContactList & ContactDetector::get () const final virtual
Get contact states.
Returns
container of contacts
Implements BipedalLocomotion::System::Advanceable< EstimatedContactList >.
Definition at line 90 of file ContactDetector.cpp.
get() [2/3]
bool ContactDetector::get (const std::string & contactName, BipedalLocomotion::Contacts::EstimatedContact & contact) const
Get state of specific contact.
Parameters
[in] contactName name of contact
[out] contact estimated contact
Returns
true if contact exists, false otherwise
Definition at line 95 of file ContactDetector.cpp.
get() [3/3]
EstimatedContact ContactDetector::get (const std::string & contactName) const
Get state of specific contact.
Parameters
[in] contactName name of contact
Returns
contact state if contact exists, a dummy contact otherwise
Definition at line 107 of file ContactDetector.cpp.
initialize()
bool ContactDetector::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configure generic parameters.
Parameters
[in] handler configure the generic parameters for the estimator
Returns
True in case of success, false otherwise.
Definition at line 13 of file ContactDetector.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
isValid()
bool ContactDetector::isValid () const final virtual
Determines the validity of the object retrieved with get()
Returns
True in case of success, false otherwise.
Implements BipedalLocomotion::System::Advanceable< EstimatedContactList >.
Definition at line 118 of file ContactDetector.cpp.
resetContacts()
bool ContactDetector::resetContacts () final virtual
Reset the internal contact states of the detector to false.
Returns
True in case of success, false otherwise.
Definition at line 79 of file ContactDetector.cpp.
updateContactStates()
bool ContactDetector::updateContactStates () protected virtual
The derived class must implement the contact detection technique to update the contact states.
Returns
True if success, false otherwise
Reimplemented in BipedalLocomotion::Estimators::SchmittTriggerDetector.
Definition at line 74 of file ContactDetector.cpp.
Field Documentation
m_detectorState
State BipedalLocomotion::Estimators::ContactDetector::m_detectorState {State::NotInitialized} protected
State of the estimator.
Definition at line 105 of file ContactDetector.h.
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/ContactDetectors/ContactDetector.h
Estimators/src/ContactDetector.cpp