bipedal-locomotion-framework: BipedalLocomotion::Planners::ContactPhaseList Class Reference
BipedalLocomotion::Planners::ContactPhaseList Class Reference
The ContactPhaseList class computes the contact phases according to a bunch of input contact lists.
#include <BipedalLocomotion/Planners/ContactPhaseList.h>
Public Types
using const_iterator = std::vector< ContactPhase >::const_iterator
Internal method to compute the phases.
using const_reverse_iterator = std::vector< ContactPhase >::const_reverse_iterator
Public Member Functions
void setLists (const ContactListMap &contactLists)
Set the input lists.
bool setLists (const std::initializer_list< ContactList > &contactLists)
Set the input lists.
const ContactListMap & lists () const
A reference to the lists stored in this class.
const_iterator begin () const
Const iterator to the begin of the phases.
const_iterator cbegin () const
Const iterator to the begin of the phases.
const_reverse_iterator rbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
const_reverse_iterator crbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
const_iterator end () const
Return a const iterator to the end of the list.
const_iterator cend () const
Return a const iterator to the end of the list.
const_reverse_iterator rend () const
Return a const reverse iterator to the end of the list.
const_reverse_iterator crend () const
Return a const reverse iterator to the end of the list.
const ContactPhase & operator[] (size_t index) const
Access phases by index.
const_iterator firstPhase () const
A const iterator to the first phase.
const_iterator lastPhase () const
A const iterator to the last phase.
size_t size () const
Get the number of phases.
void clear ()
Clear the phases and the stored lists.
Detailed Description
The ContactPhaseList class computes the contact phases according to a bunch of input contact lists.
Warning
All the iterators stored inside the contact phases refer to the lists stored within this class, not the original input lists.
Definition at line 32 of file ContactPhaseList.h.
Member Typedef Documentation
const_iterator
using BipedalLocomotion::Planners::ContactPhaseList::const_iterator = std::vector<ContactPhase>::const_iterator
Internal method to compute the phases.
Definition at line 43 of file ContactPhaseList.h.
Member Function Documentation
begin()
ContactPhaseList::const_iterator ContactPhaseList::begin () const
Const iterator to the begin of the phases.
Definition at line 116 of file ContactPhaseList.cpp.
cbegin()
ContactPhaseList::const_iterator ContactPhaseList::cbegin () const
Const iterator to the begin of the phases.
Definition at line 121 of file ContactPhaseList.cpp.
cend()
ContactPhaseList::const_iterator ContactPhaseList::cend () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 141 of file ContactPhaseList.cpp.
clear()
void ContactPhaseList::clear ()
Clear the phases and the stored lists.
Definition at line 176 of file ContactPhaseList.cpp.
References std::unordered_map< K, T >::clear().
crbegin()
ContactPhaseList::const_reverse_iterator ContactPhaseList::crbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
Definition at line 131 of file ContactPhaseList.cpp.
crend()
ContactPhaseList::const_reverse_iterator ContactPhaseList::crend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 151 of file ContactPhaseList.cpp.
end()
ContactPhaseList::const_iterator ContactPhaseList::end () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 136 of file ContactPhaseList.cpp.
firstPhase()
ContactPhaseList::const_iterator ContactPhaseList::firstPhase () const
A const iterator to the first phase.
Definition at line 161 of file ContactPhaseList.cpp.
lastPhase()
ContactPhaseList::const_iterator ContactPhaseList::lastPhase () const
A const iterator to the last phase.
Definition at line 166 of file ContactPhaseList.cpp.
lists()
const BipedalLocomotion::Planners::ContactListMap & BipedalLocomotion::Planners::ContactPhaseList::lists () const
A reference to the lists stored in this class.
Warning
All the iterators stored inside the contact phases refer to the lists viewable via this method.
Returns
A const reference to the input lists.
Definition at line 111 of file ContactPhaseList.cpp.
operator[]()
const ContactPhase & ContactPhaseList::operator[] (size_t index) const
Access phases by index.
Parameters
index of the phase to be accessed.
Returns
A const reference to the desired phase.
Definition at line 156 of file ContactPhaseList.cpp.
rbegin()
ContactPhaseList::const_reverse_iterator ContactPhaseList::rbegin () const
Const reverse iterator to the the phases (basically starting from the last phase, going backward).
Definition at line 126 of file ContactPhaseList.cpp.
rend()
ContactPhaseList::const_reverse_iterator ContactPhaseList::rend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any phase.
Definition at line 146 of file ContactPhaseList.cpp.
setLists() [1/2]
void ContactPhaseList::setLists (const ContactListMap & contactLists)
Set the input lists.
Parameters
contactLists The set of lists to be used for computing the phases.
Definition at line 86 of file ContactPhaseList.cpp.
setLists() [2/2]
bool ContactPhaseList::setLists (const std::initializer_list< ContactList > & contactLists)
Set the input lists.
Parameters
An initializer list (use as {list1, list2, ...,listN}) to the lists to be used for computing the phases. A ContactListMap will be created with the provided list, using the defaultName as a key.
Returns
False if some lists have the same defaultName.
Definition at line 92 of file ContactPhaseList.cpp.
References std::unordered_map< K, T >::clear(), std::endl(), and std::unordered_map< K, T >::insert().
size()
size_t ContactPhaseList::size () const
Get the number of phases.
Definition at line 171 of file ContactPhaseList.cpp.
The documentation for this class was generated from the following files:
Planners/include/BipedalLocomotion/Planners/ContactPhaseList.h
Planners/src/ContactPhaseList.cpp