bipedal-locomotion-framework: BipedalLocomotion::Estimators::RecursiveLeastSquare Class Reference
BipedalLocomotion::Estimators::RecursiveLeastSquare Class Reference
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handlerWeak)
Initialize the filter.
void setRegressorFunction (std::function< Eigen::MatrixXd(void)> regressor)
Set the regressor function.
void setRegressor (const Eigen::Ref< const Eigen::MatrixXd > &regressor)
Set the regressor function.
void setMeasurements (const Eigen::Ref< const Eigen::VectorXd > &measurements)
Set the measurements measurements vector containing all the measurements.
bool advance () final
Compute one step of the filter.
const RecursiveLeastSquareState & get () const final
Get the expected value and the covariance matrix of the estimated parameters.
bool isValid () const final
Determines the validity of the object retrieved with get()
Detailed Description
Definition at line 36 of file RecursiveLeastSquare.h.
Member Function Documentation
advance()
bool RecursiveLeastSquare::advance () final virtual
Compute one step of the filter.
Returns
True in case of success, false otherwise
Implements BipedalLocomotion::System::Advanceable< RecursiveLeastSquareState >.
Definition at line 100 of file RecursiveLeastSquare.cpp.
References std::endl().
get()
const RecursiveLeastSquareState & RecursiveLeastSquare::get () const final virtual
Get the expected value and the covariance matrix of the estimated parameters.
Returns
A struct containing the expected value and the covariance of the estimated parameters.
Implements BipedalLocomotion::System::Advanceable< RecursiveLeastSquareState >.
Definition at line 145 of file RecursiveLeastSquare.cpp.
initialize()
bool RecursiveLeastSquare::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > handlerWeak)
Initialize the filter.
Note
The following parameter are required by the filter:
"measurement_covariance" vector containing the covariance of the measurements. We assume that the measurements are uncorrelated (furthermore since the model of the noise is Gaussian the random variable are also independent) Since the variable are independent we are interested only on the element in the diagonal of the matrix
"lambda" double containing the filter gain. (The recursive least square filter is equivalent to a kalman filter if lambda is equal to 1)
"state" vector containing the initial guess of the state
"state_covariance" vector containing the diagonal matrix of the covariance of the state
Parameters
handlerWeak weak pointer to a ParametersHandler::IParametersHandler interface Derived particular implementation of the IParameterHandler
Returns
True in case of success, false otherwise.
Definition at line 15 of file RecursiveLeastSquare.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
isValid()
bool RecursiveLeastSquare::isValid () const final virtual
Determines the validity of the object retrieved with get()
Returns
True if the object is valid, false otherwise.
Implements BipedalLocomotion::System::Advanceable< RecursiveLeastSquareState >.
Definition at line 150 of file RecursiveLeastSquare.cpp.
setMeasurements()
void RecursiveLeastSquare::setMeasurements (const Eigen::Ref< const Eigen::VectorXd > & measurements)
Set the measurements measurements vector containing all the measurements.
Definition at line 139 of file RecursiveLeastSquare.cpp.
setRegressor()
void RecursiveLeastSquare::setRegressor (const Eigen::Ref< const Eigen::MatrixXd > & regressor)
Set the regressor function.
regressor is the regressor matrix.
Note
The user can decide to set the regressor function or set the regressor matrix by calling setReressor(). If setRegressorFunction() is called, the RLS algorithm will compute the regressor every time the advance() function is called.
Definition at line 95 of file RecursiveLeastSquare.cpp.
setRegressorFunction()
void RecursiveLeastSquare::setRegressorFunction (std::function< Eigen::MatrixXd(void)> regressor)
Set the regressor function.
regressor function that return an Eigen::MatrixXd containing the regressor of the system
Note
The user can decide to set the regressor function or set the regressor matrix by calling setReressor(). If setRegressorFunction() is called, the RLS algorithm will compute the regressor every time the advance() function is called.
Definition at line 90 of file RecursiveLeastSquare.cpp.
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/Estimators/RecursiveLeastSquare.h
Estimators/src/RecursiveLeastSquare.cpp