bipedal-locomotion-framework: BipedalLocomotion::Estimators::FloatingBaseEstimator Class Reference
BipedalLocomotion::Estimators::FloatingBaseEstimator Class Reference
FloatingBaseEstimator class contains the bare-bones implementation for a LeggedOdometry based or Extended Kalman Filter based floating base estimation algorithms for bipedal robots.
#include <BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h>
Data Structures
class ModelComputations
iDynTree based model-specific computations class This is class is used in a required configuration step for the estimator All the model related kinematics and dynamics computations specific to the floating base estimator are contained within this class.
Public Member Functions
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, const iDynTree::Model &model)
Configure generic parameters and the model.
bool setIMUMeasurement (const Eigen::Vector3d &accMeas, const Eigen::Vector3d &gyroMeas)
Set the polled IMU measurement.
bool setContacts (const bool &lfInContact, const bool &rfInContact)
Set feet contact states.
bool setKinematics (const Eigen::VectorXd &encoders, const Eigen::VectorXd &encoderSpeeds)
Set kinematic measurements.
virtual bool advance () final
Compute one step of the estimator.
virtual bool resetEstimator (const FloatingBaseEstimators::InternalState &newState) final
Reset the internal state of the estimator.
virtual bool resetEstimator (const Eigen::Quaterniond &newBaseOrientation, const Eigen::Vector3d &newBasePosition) final
Reset the base pose estimate and consequently the internal state of the estimator.
virtual const FloatingBaseEstimators::Output & get () const final
Get estimator outputs.
virtual bool isValid () const final
Determines the validity of the object retrieved with get()
ModelComputations & modelComputations ()
Get ModelComputations object by reference.
Protected Types
enum State { State::NotInitialized, State::Initialized, State::Running }
Enumerator used to determine the running state of the estimator.
Protected Member Functions
bool initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Configure generic parameters.
virtual bool customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
These custom parameter specifications should be specified by the derived class.
virtual bool predictState (const FloatingBaseEstimators::Measurements &meas, const double &dt)
Propagate the states through the prediction model, if there exists any (eg.
virtual bool updateKinematics (const FloatingBaseEstimators::Measurements &meas, const double &dt)
Update the predicted state estimates using kinematics and contact measurements.
bool setupOptions (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup estimator options.
bool setupSensorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup measurement noise standard deviations The parameters in the SensorsStdDev group are,.
bool setupInitialStates (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial states.
bool setupPriorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Setup initial state standard deviations.
Protected Attributes
ModelComputations m_modelComp
Model computations object.
FloatingBaseEstimators::Options m_options
Struct holding estimator options.
FloatingBaseEstimators::Measurements m_meas
FloatingBaseEstimators::Measurements m_measPrev
Struct holding the latest measurements that were set to the estimator.
FloatingBaseEstimators::InternalState m_state
FloatingBaseEstimators::InternalState m_statePrev
Structs holding the curent and previous internal states of the estimation algorithm.
FloatingBaseEstimators::Output m_estimatorOut
Struct holding outputs of the estimator.
FloatingBaseEstimators::StateStdDev m_priors
FloatingBaseEstimators::StateStdDev m_stateStdDev
Struct holding standard deviations associated to prior state estimates.
FloatingBaseEstimators::SensorsStdDev m_sensorsDev
Struct holding standard deviations associated to sensor measurements.
State m_estimatorState {State::NotInitialized}
State of the estimator.
double m_dt {0.01}
Fixed time step of the estimator, in seconds.
Detailed Description
FloatingBaseEstimator class contains the bare-bones implementation for a LeggedOdometry based or Extended Kalman Filter based floating base estimation algorithms for bipedal robots.
Note
it is assumed that if an IMU (primary) is specified in the inherited implementation, then this IMU is rigidly attached to the specified base link in the implementation
Definition at line 33 of file FloatingBaseEstimator.h.
Member Enumeration Documentation
State
enum BipedalLocomotion::Estimators::FloatingBaseEstimator::State strong protected
Enumerator used to determine the running state of the estimator.
Enumerator
NotInitialized
The estimator is not initialized yet call FloatingBaseEstimator::initialze method to initialize it.
Initialized
The estimator is initialized and ready to be used.
Running
The estimator is running.
Definition at line 351 of file FloatingBaseEstimator.h.
Member Function Documentation
advance()
bool FloatingBaseEstimator::advance () final virtual
Compute one step of the estimator.
Returns
True in case of success, false otherwise.
Implements BipedalLocomotion::System::Advanceable< FloatingBaseEstimators::Output >.
Definition at line 88 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::basePose, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::baseTwist, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::ekfUpdateEnabled, std::endl(), Initialized, m_dt, m_estimatorOut, m_estimatorState, m_measPrev, m_options, m_statePrev, m_stateStdDev, predictState(), Running, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::state, BipedalLocomotion::Estimators::FloatingBaseEstimators::Output::stateStdDev, and updateKinematics().
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints().
customInitialization()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::customInitialization (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) inline protected virtual
These custom parameter specifications should be specified by the derived class.
If setupOptions() is called from within customInitialization(), ensure the group "Options" exist. Please check the documentation of setupOptions() for relevant parameters
If setupSensorDevs() is called from within customInitialization(), ensure the group "SensorsStdDev" exist. Please check the documentation of setupSensorDevs() for relevant parameters
If setupInitialStates() is called from within customInitialization(), ensure the group "InitialStates" exist. Please check the documentation of setupInitialStates() for relevant parameters
If setupPriorDevs() is called from within customInitialization(), ensure the group "PriorsStdDev" exist. Please check the documentation of setupPriorDevs() for relevant parameters
Parameters
[in] handler configure the custom parameters for the estimator
Returns
bool
Reimplemented in BipedalLocomotion::Estimators::InvariantEKFBaseEstimator.
Definition at line 250 of file FloatingBaseEstimator.h.
Referenced by initialize().
get()
const FloatingBaseEstimators::Output & FloatingBaseEstimator::get () const final virtual
Get estimator outputs.
Returns
A struct containing he estimated internal states of the estiamtor and the associated covariance matrix
Implements BipedalLocomotion::System::Advanceable< FloatingBaseEstimators::Output >.
Definition at line 309 of file FloatingBaseEstimator.cpp.
References std::endl(), std::weak_ptr< T >::lock(), m_estimatorOut, m_modelComp, BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::setBaseLinkAndIMU(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::setFeetContactFrames().
initialize() [1/2]
bool FloatingBaseEstimator::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, const iDynTree::Model & model)
Configure generic parameters and the model.
The generic parameters include,
sampling_period_in_s [PARAMETER|REQUIRED|Sampling period of the estimator in seconds]
ModelInfo [GROUP|REQUIRED|URDF Model specific parameters used by the estimator]
base_link [PARAMETER|REQUIRED|base link frame from the URDF model| Exists in "ModelInfo" GROUP]
base_link_imu [PARAMETER|REQUIRED|IMU frame rigidly attached to thebase link from the URDF model| Exists in "ModelInfo" GROUP]
left_foot_contact_frame [PARAMETER|REQUIRED|left foot contact frame from the URDF model| Exists in "ModelInfo" GROUP]
right_foot_contact_frame [PARAMETER|REQUIRED|right foot contact frame from the URDF model| Exists in "ModelInfo" GROUP]
Parameters
[in] handler configure the generic parameters for the estimator
[in] model reduced iDynTree model required by the estimator
Note
any custom initialization of parameters or the algorithm implementation is not done here, it must be done in customInitialization() by the child class implementing the algorithm
Returns
True in case of success, false otherwise.
Definition at line 14 of file FloatingBaseEstimator.cpp.
References std::endl(), m_modelComp, and BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::setModel().
Referenced by isValid(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints().
initialize() [2/2]
bool FloatingBaseEstimator::initialize (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Configure generic parameters.
Parameters
[in] handler configure the generic parameters for the estimator
Returns
True in case of success, false otherwise.
Definition at line 32 of file FloatingBaseEstimator.cpp.
References customInitialization(), std::endl(), Initialized, std::weak_ptr< T >::lock(), m_dt, m_estimatorState, m_modelComp, and NotInitialized.
isValid()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::isValid () const inline final virtual
Determines the validity of the object retrieved with get()
Returns
True in case of success, false otherwise.
Implements BipedalLocomotion::System::Advanceable< FloatingBaseEstimators::Output >.
Definition at line 220 of file FloatingBaseEstimator.h.
References initialize(), m_estimatorState, modelComputations(), and Running.
modelComputations()
FloatingBaseEstimator::ModelComputations & FloatingBaseEstimator::modelComputations ()
Get ModelComputations object by reference.
Returns
ModelComputations object providing information between considered model related quantities in the estimator like the base link, IMU, feet contact frames.
Definition at line 303 of file FloatingBaseEstimator.cpp.
References m_modelComp.
Referenced by isValid(), and setKinematics().
predictState()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::predictState (const FloatingBaseEstimators::Measurements & meas, const double & dt) inline protected virtual
Propagate the states through the prediction model, if there exists any (eg.
a strap-down IMU model)
Parameters
[in] meas measurements passed as exogeneous inputs to the prediction model
[in] dt sampling period in seconds
[out] state previous state estimate
[out] P previous state covariance matrix
Returns
True in case of success, false otherwise.
Reimplemented in BipedalLocomotion::Estimators::InvariantEKFBaseEstimator.
Definition at line 260 of file FloatingBaseEstimator.h.
Referenced by advance().
resetEstimator() [1/2]
bool FloatingBaseEstimator::resetEstimator (const FloatingBaseEstimators::InternalState & newState) final virtual
Reset the internal state of the estimator.
Parameters
[in] newState Internal state of the estimator
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 706 of file FloatingBaseEstimator.cpp.
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints().
resetEstimator() [2/2]
bool FloatingBaseEstimator::resetEstimator (const Eigen::Quaterniond & newBaseOrientation, const Eigen::Vector3d & newBasePosition) final virtual
Reset the base pose estimate and consequently the internal state of the estimator.
Parameters
[in] newBaseOrientation base link orientation as a Eigen quaternion
[in] newBasePosition base link position
Returns
True in case of success, false otherwise.
Note
reset and advance estimator to get updated estimator output
Definition at line 667 of file FloatingBaseEstimator.cpp.
References std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getIMU_H_feet(), BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, m_modelComp, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFrameOrientation, and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition.
setContacts()
bool FloatingBaseEstimator::setContacts (const bool & lfInContact, const bool & rfInContact)
Set feet contact states.
Parameters
[in] lfInContact left foot contact state [0, 1]
[in] rfInContact right foot contact state [0, 1]
Returns
True in case of success, false otherwise.
Definition at line 295 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::lfInContact, and BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::rfInContact.
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints().
setIMUMeasurement()
bool FloatingBaseEstimator::setIMUMeasurement (const Eigen::Vector3d & accMeas, const Eigen::Vector3d & gyroMeas)
Set the polled IMU measurement.
Parameters
[in] accMeas linear accelerometer measurement expressed in the local IMU frame (m/s^2)
[in] gyroMeas gyroscope measurement expressed in the local IMU frame (rad/s)
Returns
True in case of success, false otherwise.
Definition at line 269 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::gyro.
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints().
setKinematics()
bool FloatingBaseEstimator::setKinematics (const Eigen::VectorXd & encoders, const Eigen::VectorXd & encoderSpeeds)
Set kinematic measurements.
Note
it is assumed that the order of the joints loaded in the model and the order of the measurements in these vectors match
Parameters
[in] encoders joint positions measured through encoders
[in] encoderSpeeds joint velocities measured through encoders
Returns
True in case of success, false otherwise.
Definition at line 279 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::encodersSpeed, std::endl(), modelComputations(), and BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints().
Referenced by BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints().
setupInitialStates()
bool FloatingBaseEstimator::setupInitialStates (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup initial states.
The parameters in the InitialStates group are,
imu_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial IMU orientation wrt inertial frame, as a quaternion]
imu_position_xyz [PARAMETER|REQUIRED|Initial IMU position wrt inertial frame]
imu_linear_velocity_xyz [PARAMETER|REQUIRED|Initial IMU linear velocity wrt inertial frame, in a mixed-velocity representation]
l_contact_frame_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial left foot contact frame orientation wrt inertial frame, as a quaternion]
l_contact_frame_position_xyz [PARAMETER|REQUIRED|Initial left foot contact frame position wrt inertial frame]
r_contact_frame_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial right foot contact frame orientation wrt inertial frame, as a quaternion]
r_contact_frame_position_xyz [PARAMETER|REQUIRED|Initial right foot contact frame position wrt inertial frame]
accelerometer_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial accelerometer bias expressed in IMU frame]
gyroscope_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial gyroscope bias expressed in IMU frame]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
ensure to call setupOptions() before calling setupInitialStates() to handle bias related parameters to be configured properly
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 497 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::accelerometerBias, std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::lContactFramePosition, std::weak_ptr< T >::lock(), m_options, m_statePrev, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFrameOrientation, and BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::rContactFramePosition.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization(), and updateKinematics().
setupOptions()
bool FloatingBaseEstimator::setupOptions (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup estimator options.
The parameters in the Options group are,
enable_imu_bias_estimation [PARAMETER|-|Enable/disable IMU bias estimation]
enable_static_imu_bias_initialization [PARAMETER|-|Enable/disable IMU bias initialization assuming static configuration]
nr_samples_for_imu_bias_initialization [PARAMETER|REQUIRED, if staticImuBiasInitializationEnabled is set to true|Number of samples for static bias initialization]
enable_ekf_update [PARAMETER|-|Enable/disable update step of EKF (not recommended to set to false)]
acceleration_due_to_gravity [PARAMETER|-|Acceleration due to gravity, 3d vector]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 370 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::accelerationDueToGravity, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::ekfUpdateEnabled, std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, std::weak_ptr< T >::lock(), m_options, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::nrSamplesForImuBiasInitialization, std::vector< T >::resize(), and BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::staticImuBiasInitializationEnabled.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization(), and updateKinematics().
setupPriorDevs()
bool FloatingBaseEstimator::setupPriorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup initial state standard deviations.
The parameters in the PriorsStdDev group are,
imu_orientation_quaternion_wxyz [PARAMETER|REQUIRED|Initial IMU orientation as wrt inertial frame]
imu_position [PARAMETER|REQUIRED|Initial IMU position deviation wrt inertial frame]
imu_linear_velocity [PARAMETER|REQUIRED|Initial IMU linear velocity deviation wrt inertial frame, in a mixed-velocity representation]
l_contact_frame_orientation_quaternion [PARAMETER|REQUIRED|Initial left foot contact frame orientation deviation wrt inertial frame]
l_contact_frame_position [PARAMETER|REQUIRED|Initial left foot contact frame position deviation wrt inertial frame]
r_contact_frame_orientation_quaternion [PARAMETER|REQUIRED|Initial right foot contact frame orientation deviation wrt inertial frame]
r_contact_frame_position [PARAMETER|REQUIRED|Initial right foot contact frame position deviation wrt inertial frame]
accelerometer_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial accelerometer bias devitaion expressed in IMU frame]
gyroscope_bias [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Initial gyroscope bias deviation expressed in IMU frame]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
ensure to call setupOptions() before calling setupPriorDevs() to handle bias related parameters to be configured properly
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 561 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::accelerometerBias, std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::getBaseStateFromIMUState(), BipedalLocomotion::Estimators::FloatingBaseEstimators::Measurements::gyro, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::gyroscopeBias, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuLinearVelocity, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::InternalState::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::imuPosition, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFrameOrientation, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::lContactFramePosition, std::weak_ptr< T >::lock(), m_modelComp, m_options, BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFrameOrientation, and BipedalLocomotion::Estimators::FloatingBaseEstimators::StateStdDev::rContactFramePosition.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization(), and updateKinematics().
setupSensorDevs()
bool FloatingBaseEstimator::setupSensorDevs (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler) protected
Setup measurement noise standard deviations The parameters in the SensorsStdDev group are,.
accelerometer_measurement_noise_std_dev [PARAMETER|REQUIRED|Accelerometer measurement white noise deviation]
gyroscope_measurement_noise_std_dev [PARAMETER|REQUIRED|Gyroscope measurement white noise deviation]
accelerometer_measurement_bias_noise_std_dev [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Accelerometer measurement bias noise deviation]
gyroscope_measurement_bias_noise_std_dev [PARAMETER|REQUIRED, if imuBiasEstimationEnabled is set to true|Gyroscope measurement bias noise deviation]
contact_foot_linear_velocity_noise_std_dev [PARAMETER|REQUIRED|Linear velocity white noise deviation when foot is in contact]
contact_foot_angular_velocity_noise_std_dev [PARAMETER|REQUIRED|Angular velocity white noise deviation when foot is in contact]
swing_foot_linear_velocity_noise_std_dev [PARAMETER|REQUIRED|Linear velocity white noise deviation when foot is swinging off contact]
swing_foot_angular_velocity_noise_std_dev [PARAMETER|REQUIRED|Angular velocity white noise deviation when foot is swinging off contact]
forward_kinematic_measurement_noise_std_dev [PARAMETER|REQUIRED|White noise deviation in relative poses computed through forward kinematics]
encoders_measurement_noise_std_dev [PARAMETER|REQUIRED|Encoder measurement white noise deviation]
Note
this is a recipe method that can be called by the derived class from within customInitialization()
ensure to call setupOptions() before calling setupSensorDevs() to handle bias related parameters to be configured properly
Parameters
[in] handler parameter handler
Returns
True in case of success, false otherwise.
Definition at line 432 of file FloatingBaseEstimator.cpp.
References BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::accelerometerNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::contactFootAngvelNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::contactFootLinvelNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::encodersNoise, std::endl(), BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::forwardKinematicsNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeBiasNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::gyroscopeNoise, BipedalLocomotion::Estimators::FloatingBaseEstimators::Options::imuBiasEstimationEnabled, std::weak_ptr< T >::lock(), m_modelComp, m_options, m_sensorsDev, BipedalLocomotion::Estimators::FloatingBaseEstimator::ModelComputations::nrJoints(), BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::swingFootAngvelNoise, and BipedalLocomotion::Estimators::FloatingBaseEstimators::SensorsStdDev::swingFootLinvelNoise.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization(), and updateKinematics().
updateKinematics()
virtual bool BipedalLocomotion::Estimators::FloatingBaseEstimator::updateKinematics (const FloatingBaseEstimators::Measurements & meas, const double & dt) inline protected virtual
Update the predicted state estimates using kinematics and contact measurements.
Parameters
[in] meas measurements to update the predicted states
[in] dt sampling period in seconds
Returns
True in case of success, false otherwise.
Reimplemented in BipedalLocomotion::Estimators::InvariantEKFBaseEstimator.
Definition at line 269 of file FloatingBaseEstimator.h.
References setupInitialStates(), setupOptions(), setupPriorDevs(), and setupSensorDevs().
Referenced by advance().
Field Documentation
m_dt
double BipedalLocomotion::Estimators::FloatingBaseEstimator::m_dt {0.01} protected
Fixed time step of the estimator, in seconds.
Definition at line 361 of file FloatingBaseEstimator.h.
Referenced by advance(), and initialize().
m_estimatorOut
FloatingBaseEstimators::Output BipedalLocomotion::Estimators::FloatingBaseEstimator::m_estimatorOut protected
Struct holding outputs of the estimator.
Definition at line 344 of file FloatingBaseEstimator.h.
Referenced by advance(), get(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator().
m_estimatorState
State BipedalLocomotion::Estimators::FloatingBaseEstimator::m_estimatorState {State::NotInitialized} protected
State of the estimator.
Definition at line 359 of file FloatingBaseEstimator.h.
Referenced by advance(), initialize(), and isValid().
m_measPrev
FloatingBaseEstimators::Measurements BipedalLocomotion::Estimators::FloatingBaseEstimator::m_measPrev protected
Struct holding the latest measurements that were set to the estimator.
Definition at line 342 of file FloatingBaseEstimator.h.
Referenced by advance(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator().
m_modelComp
ModelComputations BipedalLocomotion::Estimators::FloatingBaseEstimator::m_modelComp protected
Model computations object.
Definition at line 340 of file FloatingBaseEstimator.h.
Referenced by get(), initialize(), modelComputations(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), resetEstimator(), setupPriorDevs(), setupSensorDevs(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
m_options
FloatingBaseEstimators::Options BipedalLocomotion::Estimators::FloatingBaseEstimator::m_options protected
Struct holding estimator options.
Definition at line 341 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::customInitialization(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::resetEstimator(), setupInitialStates(), setupOptions(), setupPriorDevs(), setupSensorDevs(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::toggleBiasEstimation(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::toggleEKFUpdate(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
m_sensorsDev
FloatingBaseEstimators::SensorsStdDev BipedalLocomotion::Estimators::FloatingBaseEstimator::m_sensorsDev protected
Struct holding standard deviations associated to sensor measurements.
Definition at line 346 of file FloatingBaseEstimator.h.
Referenced by BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::resetEstimator(), setupSensorDevs(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
m_statePrev
FloatingBaseEstimators::InternalState BipedalLocomotion::Estimators::FloatingBaseEstimator::m_statePrev protected
Structs holding the curent and previous internal states of the estimation algorithm.
Definition at line 343 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), and setupInitialStates().
m_stateStdDev
FloatingBaseEstimators::StateStdDev BipedalLocomotion::Estimators::FloatingBaseEstimator::m_stateStdDev protected
Struct holding standard deviations associated to prior state estimates.
Definition at line 345 of file FloatingBaseEstimator.h.
Referenced by advance(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::InvariantEKFBaseEstimator(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::predictState(), BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::resetEstimator(), and BipedalLocomotion::Estimators::InvariantEKFBaseEstimator::updateKinematics().
The documentation for this class was generated from the following files:
Estimators/include/BipedalLocomotion/FloatingBaseEstimators/FloatingBaseEstimator.h
Estimators/src/FloatingBaseEstimator.cpp