bipedal-locomotion-framework: BipedalLocomotion::Planners::QuinticSpline Class Reference
BipedalLocomotion::Planners::QuinticSpline Class Reference
Quintic spline implement a 5-th order polynomial spline in $f{R}^n$f.
#include <BipedalLocomotion/Planners/QuinticSpline.h>
Data Structures
struct Impl
Public Member Functions
QuinticSpline ()
Constructor.
~QuinticSpline ()
Destructor.
bool setAdvanceTimeStep (const double &dt)
Set the time step of the advance interface.
bool setKnots (const std::vector< Eigen::VectorXd > &position, const std::vector< double > &time)
Set the knots of the spline.
bool setInitialConditions (Eigen::Ref< const Eigen::VectorXd > velocity, Eigen::Ref< const Eigen::VectorXd > acceleration)
Set the initial condition of the spline.
bool setFinalConditions (Eigen::Ref< const Eigen::VectorXd > velocity, Eigen::Ref< const Eigen::VectorXd > acceleration)
Set the final condition of the spline.
bool evaluatePoint (const double &t, Eigen::Ref< Eigen::VectorXd > position, Eigen::Ref< Eigen::VectorXd > velocity, Eigen::Ref< Eigen::VectorXd > acceleration)
Evaluate the spline at a given point.
bool evaluatePoint (const double &t, QuinticSplineState &state)
Evaluate the spline at a given point.
const QuinticSplineState & get () const final
Get the state of the system.
bool isValid () const final
Determines the validity of the object retrieved with get()
bool advance () final
Advance the internal state.
Detailed Description
Quintic spline implement a 5-th order polynomial spline in $f{R}^n$f.
Definition at line 33 of file QuinticSpline.h.
Constructor & Destructor Documentation
QuinticSpline()
QuinticSpline::QuinticSpline ()
Constructor.
Definition at line 175 of file QuinticSpline.cpp.
References ~QuinticSpline().
~QuinticSpline()
QuinticSpline::~QuinticSpline () default
Destructor.
Note
It is required by the PIMPL idiom.
Referenced by QuinticSpline().
Member Function Documentation
advance()
bool QuinticSpline::advance () final virtual
Advance the internal state.
This may change the value retrievable from get().
Warning
if the the time step of the advance is not set the user cannot use the advance features.
Returns
True if the advance is successfull.
Implements BipedalLocomotion::System::Advanceable< QuinticSplineState >.
Definition at line 857 of file QuinticSpline.cpp.
References std::endl(), evaluatePoint(), isValid(), and std::min().
evaluatePoint() [1/2]
bool QuinticSpline::evaluatePoint (const double & t, Eigen::Ref< Eigen::VectorXd > position, Eigen::Ref< Eigen::VectorXd > velocity, Eigen::Ref< Eigen::VectorXd > acceleration)
Evaluate the spline at a given point.
Parameters
t instant time
position position at time t
velocity velocity at time t
acceleration acceleration at time t
Returns
True in case of success, false otherwise.
Definition at line 788 of file QuinticSpline.cpp.
References std::endl(), std::find_if(), and BipedalLocomotion::Planners::QuinticSpline::Impl::polynomials.
Referenced by advance(), evaluatePoint(), BipedalLocomotion::Planners::SwingFootPlanner::get(), and BipedalLocomotion::Planners::TimeVaryingDCMPlanner::Impl::setupCasADiFunctions().
evaluatePoint() [2/2]
bool QuinticSpline::evaluatePoint (const double & t, QuinticSplineState & state)
Evaluate the spline at a given point.
Parameters
t instant time
state of the system
Returns
True in case of success, false otherwise.
Definition at line 844 of file QuinticSpline.cpp.
References evaluatePoint().
get()
const QuinticSplineState & QuinticSpline::get () const final virtual
Get the state of the system.
Warning
if the the time step of the advance is not set the user cannot use the advance features.
Returns
a const reference of the requested object.
Implements BipedalLocomotion::System::Advanceable< QuinticSplineState >.
Definition at line 878 of file QuinticSpline.cpp.
isValid()
bool QuinticSpline::isValid () const final virtual
Determines the validity of the object retrieved with get()
Warning
if the the time step of the advance is not set the user cannot use the advance features.
Returns
True if the object is valid, false otherwise.
Implements BipedalLocomotion::System::Advanceable< QuinticSplineState >.
Definition at line 849 of file QuinticSpline.cpp.
Referenced by advance().
setAdvanceTimeStep()
bool QuinticSpline::setAdvanceTimeStep (const double & dt)
Set the time step of the advance interface.
Warning
if the the time step is not set the user cannot use the advance features.
Parameters
dt the time step of the advance block.
Returns
True in case of success, false otherwise.
Definition at line 226 of file QuinticSpline.cpp.
References std::endl().
setFinalConditions()
bool QuinticSpline::setFinalConditions (Eigen::Ref< const Eigen::VectorXd > velocity, Eigen::Ref< const Eigen::VectorXd > acceleration)
Set the final condition of the spline.
Parameters
velocity final velocity (i.e. first derivative).
acceleration final acceleration (i.e. second derivative).
Returns
True in case of success, false otherwise.
Definition at line 206 of file QuinticSpline.cpp.
References std::endl().
Referenced by BipedalLocomotion::Planners::SwingFootPlanner::initialize(), and BipedalLocomotion::Planners::TimeVaryingDCMPlanner::Impl::setupCasADiFunctions().
setInitialConditions()
bool QuinticSpline::setInitialConditions (Eigen::Ref< const Eigen::VectorXd > velocity, Eigen::Ref< const Eigen::VectorXd > acceleration)
Set the initial condition of the spline.
Parameters
velocity initial velocity (i.e. first derivative).
acceleration initial acceleration (i.e. second derivative).
Returns
True in case of success, false otherwise.
Definition at line 182 of file QuinticSpline.cpp.
References std::endl().
Referenced by BipedalLocomotion::Planners::SwingFootPlanner::initialize(), and BipedalLocomotion::Planners::TimeVaryingDCMPlanner::Impl::setupCasADiFunctions().
setKnots()
bool QuinticSpline::setKnots (const std::vector< Eigen::VectorXd > & position, const std::vector< double > & time)
Set the knots of the spline.
Parameters
position position of the knots in $f{R}^n$f.
time vector containing the time instant of the knots.
Returns
True in case of success, false otherwise.
Definition at line 241 of file QuinticSpline.cpp.
References std::endl(), std::vector< T >::front(), and std::vector< T >::size().
Referenced by BipedalLocomotion::Planners::SwingFootPlanner::advance(), and BipedalLocomotion::Planners::TimeVaryingDCMPlanner::Impl::setupCasADiFunctions().
The documentation for this class was generated from the following files:
Planners/include/BipedalLocomotion/Planners/QuinticSpline.h
Planners/src/QuinticSpline.cpp