bipedal-locomotion-framework: BipedalLocomotion::TSID::SE3Task Class Reference
BipedalLocomotion::TSID::SE3Task Class Reference
SE3Task is a concrete implementation of the OptimalControlElement.
#include <BipedalLocomotion/TSID/SE3Task.h>
Public Member Functions
bool initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler, const System::VariablesHandler &variablesHandler) override
Initialize the planner.
bool update () override
Update the content of the element.
bool setReferenceTrajectory (const manif::SE3d &I_H_F, const manif::SE3d::Tangent &mixedVelocity, const manif::SE3d::Tangent &mixedAcceleration)
Set the desired reference trajectory.
Public Member Functions inherited from BipedalLocomotion::TSID::Task
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set the kinDynComputations object.
Eigen::Ref< const Eigen::MatrixXd > getA () const
Get the matrix A.
Eigen::Ref< const Eigen::VectorXd > getB () const
Get the vector b.
const std::string & getDescription () const
Get the description of the element.
Additional Inherited Members
Protected Member Functions inherited from BipedalLocomotion::TSID::Task
iDynTree::MatrixView< double > subA (const System::VariablesHandler::VariableDescription &description)
Extract the submatrix A associated to a given variable.
iDynTree::MatrixView< const double > subA (const System::VariablesHandler::VariableDescription &description) const
Extract the submatrix A associated to a given variable.
Protected Attributes inherited from BipedalLocomotion::TSID::Task
Eigen::MatrixXd m_A
Element Matrix.
Eigen::VectorXd m_b
Element Vector.
std::string m_description {"Generic Optimal Control Element"}
String describing the content of the element.
std::shared_ptr< iDynTree::KinDynComputations > m_kinDyn
Pointer to a KinDynComputations object.
Detailed Description
SE3Task is a concrete implementation of the OptimalControlElement.
Please use this element if you want to control the position and the orientation of a given frame rigidly attached to the robot. The task assumes perfect control of the robot acceleration \(\dot{\nu}\) that contains the base linear and angular acceleration expressed in mixed representation and the joints acceleration. The task represents the following equation
\[ J \dot{\nu} + \dot{J} \nu = \dot{\mathrm{v}} ^ * \]
where \(J\) is the robot jacobian and \(\dot{\mathrm{v}} ^ *\) is the desired acceleration. The desired acceleration is chosen such that the frame will asymptotically converge to the desired trajectory. The linear component of \(\dot{\mathrm{v}} ^ *\) is computed with a standard PD controller in \(R^3\) while the angular acceleration is computed by a PD controller in \(SO(3)\).
Note
Please refer to https://github.com/dic-iit/lie-group-controllers if you are interested in the implementation of the PD controllers.
The SE3Task is technically not a \(SE(3)\) space defined task, instead is a \(SO(3) \times \mathbb{R}^3\) task. Theoretically, there are differences between the two due to the different definitions of exponential maps and logarithm maps. Please consider that here the MIXED representation is used to define the 6d-velocity. You can find further details in Section 2.3.4 of https://traversaro.github.io/phd-thesis/traversaro-phd-thesis.pdf.
Definition at line 44 of file SE3Task.h.
Member Function Documentation
initialize()
bool SE3Task::initialize (std::weak_ptr< ParametersHandler::IParametersHandler > paramHandler, const System::VariablesHandler & variablesHandler) override virtual
Initialize the planner.
Parameters
paramHandler pointer to the parameters handler.
variablesHandler reference to a variables handler.
Note
the following parameters are required by the class
Parameter Name Type Description Mandatory
robot_acceleration_variable_name string Name of the variable contained in VariablesHandler describing the robot acceleration Yes
frame_name string Name of the frame controlled by the SE3Task Yes
kp_linear double Gain of the position controller Yes
kd_linear double Gain of the linear velocity controller Yes
kp_angular double Gain of the orientation controller Yes
kd_angular double Gain of the angular velocity controller Yes
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::TSID::Task.
Definition at line 18 of file SE3Task.cpp.
References std::endl(), BipedalLocomotion::System::VariablesHandler::getNumberOfVariables(), BipedalLocomotion::System::VariablesHandler::getVariable(), std::weak_ptr< T >::lock(), and std::string::resize().
setReferenceTrajectory()
bool SE3Task::setReferenceTrajectory (const manif::SE3d & I_H_F, const manif::SE3d::Tangent & mixedVelocity, const manif::SE3d::Tangent & mixedAcceleration)
Set the desired reference trajectory.
Parameters
I_H_F Homogeneous transform between the link and the inertial frame.
mixedVelocity 6D-velocity written in mixed representation.
mixedAcceleration 6D-acceleration written in mixed representation.
Returns
True in case of success, false otherwise.
Definition at line 143 of file SE3Task.cpp.
update()
bool SE3Task::update () override virtual
Update the content of the element.
Returns
True in case of success, false otherwise.
Reimplemented from BipedalLocomotion::TSID::Task.
Definition at line 112 of file SE3Task.cpp.
References std::endl().
The documentation for this class was generated from the following files:
TSID/include/BipedalLocomotion/TSID/SE3Task.h
TSID/src/SE3Task.cpp