bipedal-locomotion-framework: BipedalLocomotion::System::FloatingBaseDynamicalSystem Class Reference
BipedalLocomotion::System::FloatingBaseDynamicalSystem Class Reference
FloatingBaseDynamicalSystem describes a floating base dynamical system.
#include <BipedalLocomotion/System/FloatingBaseSystemDynamics.h>
Public Member Functions
FloatingBaseDynamicalSystem ()
Constructor.
bool initalize (std::weak_ptr< ParametersHandler::IParametersHandler > handler) override
Initialize the Dynamical system.
void setGravityVector (const Eigen::Ref< const Eigen::Vector3d > &gravity)
Set the vector of gravity.
bool setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set a kinDynComputations object.
Public Member Functions inherited from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::VectorXd, std::vector< ContactWrench > > >
virtual bool setState (const StateType &state)
Set the state of the dynamical system.
const StateType & getState () const
Get the state to the dynamical system.
virtual bool setControlInput (const InputType &controlInput)
Set the control input to the dynamical system.
virtual bool dynamics (const double &time, StateDerivativeType &stateDerivative)=0
Computes the system dynamics.
~DynamicalSystem ()=default
Destructor.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::VectorXd, std::vector< ContactWrench > > >
using StateType = std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >
State space type.
using StateDerivativeType = std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >
State space derivative type.
using InputType = std::tuple< Eigen::VectorXd, std::vector< ContactWrench > >
Input type.
Protected Attributes inherited from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::VectorXd, std::vector< ContactWrench > > >
InputType m_controlInput
Value of the control input.
StateType m_state
Value of the current state of the system.
Detailed Description
FloatingBaseDynamicalSystem describes a floating base dynamical system.
The FloatingBaseDynamicalSystem inherits from a generic DynamicalSystem where:
DynamicalSystem::StateType is described by an std::tuple containing:
Eigen::Vector6d: the base velocity expressed in mixed representation;
Eigen::VectorXd: the joint velocities [in rad/s];
Eigen::Vector3d: position of the base w.r.t. the inertial frame
Eigen::Matrix3d: rotation matrix \({} ^ I R _ {b}\). Matrix that transform a vector whose coordinates are expressed in the base frame in the inertial frame;
Eigen::VectorXd: the joint positions [in rad].
DynamicalSystem::StateDerivativeType is described by an std::tuple containing:
Eigen::Vector6d: the base acceleration expressed in mixed representation;
Eigen::VectorXd: the joint accelerations [in rad/s^2];
Eigen::Vector3d: base velocity w.r.t. the inertial frame;
Eigen::Matrix3d: rate of change of the rotation matrix \({} ^ I \dot{R} _ {b}\). whose coordinates are expressed in the base frame in the inertial frame;
Eigen::VectorXd: the joint velocities [in rad/s].
DynamicalSystem::InputType is described by an std::tuple containing:
Eigen::VectorXd: the joint torques [in Nm];
std::vector<ContactWrench>: List of contact wrenches.
Definition at line 47 of file FloatingBaseSystemDynamics.h.
Constructor & Destructor Documentation
FloatingBaseDynamicalSystem()
FloatingBaseDynamicalSystem::FloatingBaseDynamicalSystem ()
Constructor.
Note
The constructor set the gravity acceleration vector to \(\begin{bmatrix} 0 & 0 & -9.81\end{bmatrix}^\top\). Please call setGravityVector() if you want define your custom gravity vector.
Definition at line 43 of file FloatingBaseSystemDynamics.cpp.
Member Function Documentation
initalize()
bool FloatingBaseDynamicalSystem::initalize (std::weak_ptr< ParametersHandler::IParametersHandler > handler) override virtual
Initialize the Dynamical system.
Note
Please call this function only if you want to set an arbitrary value for the parameter used in the Baumgarte stabilization \(\rho\) (The default value is 0.01). In this case the handler should contain a key called rho.
Parameters
handler pointer to the parameter handler.
Returns
true in case of success/false otherwise.
Reimplemented from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::VectorXd, std::vector< ContactWrench > > >.
Definition at line 19 of file FloatingBaseSystemDynamics.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
setGravityVector()
void FloatingBaseDynamicalSystem::setGravityVector (const Eigen::Ref< const Eigen::Vector3d > & gravity)
Set the vector of gravity.
Parameters
gravity a 3D vector describing the gravity acceleration.
Definition at line 50 of file FloatingBaseSystemDynamics.cpp.
setKinDyn()
bool FloatingBaseDynamicalSystem::setKinDyn (std::shared_ptr< iDynTree::KinDynComputations > kinDyn)
Set a kinDynComputations object.
Parameters
kinDyn a pointer to the kinDynComputations object.
Returns
true in case of success, false otherwise.
Definition at line 55 of file FloatingBaseSystemDynamics.cpp.
References BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd, Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::VectorXd, std::vector< ContactWrench > > >::dynamics(), and std::endl().
The documentation for this class was generated from the following files:
System/include/BipedalLocomotion/System/FloatingBaseSystemDynamics.h
System/src/FloatingBaseSystemDynamics.cpp