bipedal-locomotion-framework: BipedalLocomotion::Planners::ContactList Class Reference
BipedalLocomotion::Planners::ContactList Class Reference
Class containing a list of contacts.
#include <BipedalLocomotion/Planners/ContactList.h>
Public Types
using const_iterator = std::set< Contact, ContactCompare >::const_iterator
Default contact type.
using const_reverse_iterator = std::set< Contact, ContactCompare >::const_reverse_iterator
Public Member Functions
void setDefaultName (const std::string &defaultName)
Set the default name.
const std::string & defaultName () const
Get the default name.
void setDefaultContactType (const ContactType &type)
Set the default contact type.
const ContactType & defaultContactType () const
Get the default contact type.
bool addContact (const Contact &newContact)
Add a new contact to the list.
bool addContact (const manif::SE3d &newTransform, double activationTime, double deactivationTime)
Add a new contact to the list.
const_iterator erase (const_iterator iterator)
Erase a contact.
const_iterator begin () const
Return a const iterator to the begin of the contacts.
const_iterator cbegin () const
Return a const iterator to the begin of the contacts.
const_reverse_iterator rbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
const_reverse_iterator crbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
const_iterator end () const
Return a const iterator to the end of the list.
const_iterator cend () const
Return a const iterator to the end of the list.
const_reverse_iterator rend () const
Return a const reverse iterator to the end of the list.
const_reverse_iterator crend () const
Return a const reverse iterator to the end of the list.
const Contact & operator[] (size_t index) const
Access contacts by index.
size_t size () const
Get the size of the list.
const_iterator firstContact () const
Iterator pointing to the first contact.
const_iterator lastContact () const
Iterator pointing to the last contact.
bool editContact (const_iterator element, const Contact &newContact)
Edit an existing contact.
const_iterator getPresentContact (double time) const
Get the contact given the time.
bool keepOnlyPresentContact (double time)
Clear all the steps, except the one returned by getPresentContact.
void clear ()
Clear the contacts.
void removeLastContact ()
Remove only the last contact.
Detailed Description
Class containing a list of contacts.
The contact are added such that the activation time is strictly growing. In addition, contacts cannot be overlapping. It represents a series of contact activations and deactivations of a single entity.
Definition at line 32 of file ContactList.h.
Member Typedef Documentation
const_iterator
using BipedalLocomotion::Planners::ContactList::const_iterator = std::set<Contact, ContactCompare>::const_iterator
Default contact type.
Definition at line 47 of file ContactList.h.
Member Function Documentation
addContact() [1/2]
bool ContactList::addContact (const Contact & newContact)
Add a new contact to the list.
Parameters
newContact The new contact
Returns
false if it was not possible to insert the contact. Possible failures: the activation time is greater than the deactivation time, or the new contact ovelaps with an existing contact.
Definition at line 40 of file ContactList.cpp.
References BipedalLocomotion::Planners::Contact::activationTime, BipedalLocomotion::Planners::Contact::deactivationTime, end(), std::endl(), and std::set< K >::insert().
Referenced by addContact(), and keepOnlyPresentContact().
addContact() [2/2]
bool ContactList::addContact (const manif::SE3d & newTransform, double activationTime, double deactivationTime)
Add a new contact to the list.
It uses the defaultName and the defaultContactType for the missing informations.
Parameters
newTransform The contact pose.
activationTime The activation time.
deactivationTime The deactivation time.
Returns
false if it was not possible to insert the contact. Possible failures: the activation time is greater than the deactivation time, or the new contact ovelaps with an existing contact.
Definition at line 64 of file ContactList.cpp.
References BipedalLocomotion::Planners::Contact::activationTime, addContact(), BipedalLocomotion::Planners::Contact::deactivationTime, BipedalLocomotion::Planners::Contact::name, BipedalLocomotion::Planners::Contact::pose, and BipedalLocomotion::Planners::Contact::type.
begin()
ContactList::const_iterator ContactList::begin () const
Return a const iterator to the begin of the contacts.
Definition at line 81 of file ContactList.cpp.
References std::set< K >::begin().
Referenced by editContact(), firstContact(), and operator[]().
cbegin()
ContactList::const_iterator ContactList::cbegin () const
Return a const iterator to the begin of the contacts.
Definition at line 86 of file ContactList.cpp.
References std::set< K >::cbegin().
cend()
ContactList::const_iterator ContactList::cend () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 106 of file ContactList.cpp.
References std::set< K >::cend().
clear()
void ContactList::clear ()
Clear the contacts.
Definition at line 222 of file ContactList.cpp.
References std::set< K >::clear().
Referenced by keepOnlyPresentContact().
crbegin()
ContactList::const_reverse_iterator ContactList::crbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
Definition at line 96 of file ContactList.cpp.
References std::set< K >::crbegin().
crend()
ContactList::const_reverse_iterator ContactList::crend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 116 of file ContactList.cpp.
References std::set< K >::crend().
defaultContactType()
const ContactType & ContactList::defaultContactType () const
Get the default contact type.
Returns
the default contact type.
Definition at line 35 of file ContactList.cpp.
defaultName()
const std::string & ContactList::defaultName () const
Get the default name.
Returns
the default name.
Definition at line 25 of file ContactList.cpp.
Referenced by setDefaultName().
editContact()
bool ContactList::editContact (ContactList::const_iterator element, const Contact & newContact)
Edit an existing contact.
Parameters
element Iterator to the element to edit.
newContact The new contact
Returns
false if the element is not valid or if the new contact timing would require a reordering of the list.
Definition at line 154 of file ContactList.cpp.
References BipedalLocomotion::Planners::Contact::activationTime, begin(), BipedalLocomotion::Planners::Contact::deactivationTime, end(), std::endl(), std::set< K >::erase(), and std::set< K >::insert().
end()
ContactList::const_iterator ContactList::end () const
Return a const iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 101 of file ContactList.cpp.
References std::set< K >::end().
Referenced by addContact(), BipedalLocomotion::Planners::SwingFootPlanner::advance(), editContact(), getPresentContact(), keepOnlyPresentContact(), and lastContact().
erase()
ContactList::const_iterator ContactList::erase (const_iterator iterator)
Erase a contact.
Parameters
iterator to the contact to erase.
Returns
an iterator to the contact that follows the one removed.
Definition at line 76 of file ContactList.cpp.
References std::set< K >::erase().
Referenced by removeLastContact().
firstContact()
ContactList::const_iterator ContactList::firstContact () const
Iterator pointing to the first contact.
Definition at line 144 of file ContactList.cpp.
References begin().
Referenced by BipedalLocomotion::Planners::SwingFootPlanner::setContactList().
getPresentContact()
ContactList::const_iterator ContactList::getPresentContact (double time) const
Get the contact given the time.
It returns the contact with the highest activation time lower than time. If no contacts have an activation time lower than time, it returns an iterator to the end. Notice that the contact may not be active, i.e. the deactivationTime may be lower than time.
Parameters
time The present time.
Returns
an iterator to the last contact having an activation time lower than time. If no contact satisfy this condition, it returns a pointer to the end.
Definition at line 190 of file ContactList.cpp.
References BipedalLocomotion::Planners::Contact::activationTime, end(), std::find_if(), rbegin(), and rend().
Referenced by keepOnlyPresentContact().
keepOnlyPresentContact()
bool ContactList::keepOnlyPresentContact (double time)
Clear all the steps, except the one returned by getPresentContact.
Parameters
time The present time.
Returns
false if no contact is available at this time.
Definition at line 204 of file ContactList.cpp.
References addContact(), clear(), end(), std::endl(), and getPresentContact().
lastContact()
ContactList::const_iterator ContactList::lastContact () const
Iterator pointing to the last contact.
Definition at line 149 of file ContactList.cpp.
References end().
Referenced by BipedalLocomotion::Planners::SwingFootPlanner::advance(), and removeLastContact().
operator[]()
const Contact & ContactList::operator[] (size_t index) const
Access contacts by index.
Warning
This method in a for loop is much less efficient than using iterators.
Parameters
index of the phase to be accessed.
Returns
A const reference to the desired contact.
Definition at line 121 of file ContactList.cpp.
References std::advance(), begin(), rbegin(), and size().
rbegin()
ContactList::const_reverse_iterator ContactList::rbegin () const
Return a const reverse iterator to the contacts (basically starting from the last contact going backward).
Definition at line 91 of file ContactList.cpp.
References std::set< K >::rbegin().
Referenced by getPresentContact(), and operator[]().
removeLastContact()
void ContactList::removeLastContact ()
Remove only the last contact.
Definition at line 227 of file ContactList.cpp.
References erase(), and lastContact().
rend()
ContactList::const_reverse_iterator ContactList::rend () const
Return a const reverse iterator to the end of the list.
This is only a placeholder, it does not reference any contact.
Definition at line 111 of file ContactList.cpp.
References std::set< K >::rend().
Referenced by getPresentContact().
setDefaultContactType()
void ContactList::setDefaultContactType (const ContactType & type)
Set the default contact type.
Parameters
The default contact type.
Definition at line 30 of file ContactList.cpp.
setDefaultName()
void ContactList::setDefaultName (const std::string & defaultName)
Set the default name.
Parameters
defaultName the default name.
Definition at line 20 of file ContactList.cpp.
References defaultName().
size()
size_t ContactList::size () const
Get the size of the list.
Returns
The number of contacts.
Definition at line 139 of file ContactList.cpp.
References std::set< K >::size().
Referenced by BipedalLocomotion::Planners::SwingFootPlanner::isValid(), and operator[]().
The documentation for this class was generated from the following files:
Planners/include/BipedalLocomotion/Planners/ContactList.h
Planners/src/ContactList.cpp