bipedal-locomotion-framework: BipedalLocomotion::System::FloatingBaseSystemKinematics Class Reference
BipedalLocomotion::System::FloatingBaseSystemKinematics Class Reference
FloatingBaseSystemKinematics describes a floating base system kinematics.
#include <BipedalLocomotion/System/FloatingBaseSystemKinematics.h>
Public Member Functions
bool initalize (std::weak_ptr< ParametersHandler::IParametersHandler > handler) override
Initialize the Dynamical system.
bool dynamics (const double &time, StateDerivativeType &stateDerivative) final
Computes the floating based system dynamics.
~FloatingBaseSystemKinematics ()=default
Destructor.
Public Member Functions inherited from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd > >
virtual bool setState (const StateType &state)
Set the state of the dynamical system.
const StateType & getState () const
Get the state to the dynamical system.
virtual bool setControlInput (const InputType &controlInput)
Set the control input to the dynamical system.
virtual bool dynamics (const double &time, StateDerivativeType &stateDerivative)=0
Computes the system dynamics.
~DynamicalSystem ()=default
Destructor.
Additional Inherited Members
Public Types inherited from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd > >
using StateType = std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >
State space type.
using StateDerivativeType = std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >
State space derivative type.
using InputType = std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd >
Input type.
Protected Attributes inherited from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd > >
InputType m_controlInput
Value of the control input.
StateType m_state
Value of the current state of the system.
Detailed Description
FloatingBaseSystemKinematics describes a floating base system kinematics.
The FloatingBaseSystemKinematics inherits from a generic DynamicalSystem where:
DynamicalSystem::StateType is described by an std::tuple containing:
Eigen::Vector6d: position of the base w.r.t. the inertial frame
Eigen::Matrix3d: rotation matrix \({} ^ I R _ {b}\). Matrix that transform a vector whose coordinates are expressed in the base frame in the inertial frame;
Eigen::VectorXd: the joint positions [in rad].
DynamicalSystem::StateDerivativeType is described by an std::tuple containing:
Eigen::Vector6d: base velocity w.r.t. the inertial frame;
Eigen::Matrix3d: rate of change of the rotation matrix \({} ^ I \dot{R} _ {b}\). whose coordinates are expressed in the base frame in the inertial frame;
Eigen::VectorXd: the joint velocities [in rad/s].
DynamicalSystem::InputType is described by an std::tuple containing:
Eigen::Vector6d: base twist w.r.t. the inertial frame;
Eigen::VectorXd: the joint velocities [in rad/s].
Definition at line 42 of file FloatingBaseSystemKinematics.h.
Constructor & Destructor Documentation
~FloatingBaseSystemKinematics()
BipedalLocomotion::System::FloatingBaseSystemKinematics::~FloatingBaseSystemKinematics () default
Destructor.
Member Function Documentation
dynamics()
bool FloatingBaseSystemKinematics::dynamics (const double & time, StateDerivativeType & stateDerivative) final
Computes the floating based system dynamics.
It return \(f(x, u, t)\).
Note
The control input and the state have to be set separately with the methods setControlInput and setState.
Parameters
time the time at witch the dynamics is computed.
stateDynamics tuple containing a reference to the element of the state derivative
Returns
true in case of success, false otherwise.
Definition at line 36 of file FloatingBaseSystemKinematics.cpp.
References std::endl().
initalize()
bool FloatingBaseSystemKinematics::initalize (std::weak_ptr< ParametersHandler::IParametersHandler > handler) override virtual
Initialize the Dynamical system.
Note
Please call this function only if you want to set an arbitrary value for the parameter used in the Baumgarte stabilization \(\rho\) (The default value is 0.01). In this case the handler should contain a key called rho.
Parameters
handler pointer to the parameter handler.
Returns
true in case of success/false otherwise.
Reimplemented from BipedalLocomotion::System::DynamicalSystem< std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Vector3d, Eigen::Matrix3d, Eigen::VectorXd >, std::tuple< Eigen::Matrix< double, 6, 1 >, Eigen::VectorXd > >.
Definition at line 13 of file FloatingBaseSystemKinematics.cpp.
References std::endl(), and std::weak_ptr< T >::lock().
The documentation for this class was generated from the following files:
System/include/BipedalLocomotion/System/FloatingBaseSystemKinematics.h
System/src/FloatingBaseSystemKinematics.cpp