bipedal-locomotion-framework: BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl Struct Reference
BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl Struct Reference
Data Structures
struct ControlBoardRemapperInterfaces
Struct holding remapped remote control board interfaces.
struct ControlBoardRemapperMeasures
Struct holding measurements polled from remapped remote control board interfaces.
struct MASSensorIndexMaps
struct WholeBodyMASForceTorquesInterface
Struct holding remapped MAS interfaces - FT sensors related.
struct WholeBodyMASInertialsInterface
Struct holding remapped MAS interfaces -inertial sensors related.
Public Types
using StampedYARPVector = std::pair< yarp::sig::Vector, double >
using StampedYARPImage = std::pair< yarp::sig::Image, double >
using SubConfigLoader = bool(YarpSensorBridge::Impl::*)(std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler >, SensorBridgeMetaData &)
Public Member Functions
bool getIndexFromVector (const std::vector< std::string > &vec, const std::string &query, int &index)
Utility function to get index from vector.
bool nanExistsInVec (const yarp::sig::Vector &vec, std::string_view logPrefix, const std::string &sensorName)
Utility function to check for nan in vector.
bool subConfigLoader (const std::string &enableStreamString, const std::string &streamGroupString, const SubConfigLoader loader, std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData &metaData, bool &enableStreamFlag)
Checks is a stream is enabled in configuration and loads the relevant stream group from configuration.
bool configureRemoteControlBoardRemapper (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData &metaData)
Configure remote control board remapper meta data Related to kinematics and other joint/motor relevant quantities.
bool configureInertialSensors (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData &metaData)
Configure inertial sensors meta data.
bool configureSixAxisForceTorqueSensors (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData &metaData)
Configure six axis force torque sensors meta data.
bool configureCartesianWrenches (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData &metaData)
Configure cartesian wrenches meta data.
template<typename SensorType >
bool attachGenericOrAnalogSensor (const yarp::dev::PolyDriverList &devList, const std::string &sensorName, const int &nrChannelsInSensor, std::unordered_map< std::string, SensorType *> &sensorMap)
Attach device with IGenericSensor or IAnalogSensor interfaces Important assumptions here,.
template<typename SensorType >
bool attachAllGenericOrAnalogSensors (const yarp::dev::PolyDriverList &devList, std::unordered_map< std::string, SensorType *> &sensorMap, const int &nrChannelsInSensor, const std::vector< std::string > &sensorList, std::string_view interfaceType)
template<typename MASSensorType >
bool attachAndCheckMASSensors (const yarp::dev::PolyDriverList &devList, MASSensorType *&sensorInterface, const std::vector< std::string > &sensorList, const std::string_view interfaceName)
Attach Remapped Multiple Analog Sensor Interfaces and check available sensors.
template<typename MASSensorType >
bool attachRemappedMASSensor (const yarp::dev::PolyDriverList &devList, MASSensorType *&masSensorInterface)
Attach Remapped Multiple Analog Sensor Interfaces Looks for a specific MAS Sensor interface in the attached MAS Remapper.
template<typename MASSensorType >
bool checkAttachedMASSensors (const yarp::dev::PolyDriverList &devList, MASSensorType *&sensorInterface, const std::vector< std::string > &sensorList)
Check if all the desired MAS sensors are availabled in the attached MAS interface.
template<typename MASSensorType >
std::size_t getNumberOfMASSensors (MASSensorType *&sensorInterface)
Get number of MAS Sensors.
template<typename MASSensorType >
bool getMASSensorName (MASSensorType *&sensorInterface, const std::size_t &sensIdx, std::string &sensorName)
Get name of MAS Sensors.
template<typename MASSensorType >
std::vector< std::string > getAllSensorsInMASInterface (MASSensorType *sensorInterface)
Get all sensor names in a MAS Inerface.
template<typename SensorType >
bool checkSensor (const std::unordered_map< std::string, SensorType * > &sensorMap, const std::string &sensorName)
Check if sensor is available in the relevant sensor map.
template<typename YARPDataType >
bool checkValidSensorMeasure (std::string_view logPrefix, const std::unordered_map< std::string, YARPDataType > &sensorMap, const std::string &sensorName)
Check if sensor is available in the relevant sensor measurement map.
bool checkValid (const std::string_view methodName)
Check if the bridge is successfully initialized and attached to required device drivers.
bool attachAllInertials (const yarp::dev::PolyDriverList &devList)
Attach generic IMU sensor types and MAS inertials.
bool attachRemappedRemoteControlBoard (const yarp::dev::PolyDriverList &devList)
Attach a remapped control board and check the availability of desired interface Further, resize joint data buffers and check if the control board joints list and the desired joints list match Also, maintain a remapping index buffer for adapting to arbitrary joint list serializations.
void resetControlBoardBuffers ()
resize and set control board buffers to zero
bool compareControlBoardJointsList ()
check and match control board joints with the sensorbridge joints list
bool attachAllSixAxisForceTorqueSensors (const yarp::dev::PolyDriverList &devList)
bool attachCartesianWrenchInterface (const yarp::dev::PolyDriverList &devList)
Attach to cartesian wrench interface.
double deg2rad (double deg)
utility function
template<typename SensorType >
bool readAnalogOrGenericSensor (const std::string &sensorName, const int &nrChannelsInYARPSensor, std::unordered_map< std::string, SensorType * > &interfaceMap, std::unordered_map< std::string, StampedYARPVector > &measurementMap, bool checkForNan=false)
Read generic or analog sensor stream and update internal measurement buffer.
template<typename MASSensorType >
bool readMASSensor (MASSensorType *interface, const std::string &sensorName, const std::unordered_map< std::string, std::size_t > &sensorIdxMap, std::unordered_map< std::string, StampedYARPVector > &measurementMap, bool checkForNan=false)
template<typename MASSensorType >
bool readAllMASSensors (MASSensorType *interface, std::unordered_map< std::string, std::size_t > sensIdxMap, std::unordered_map< std::string, StampedYARPVector > &measurementMap, std::vector< std::string > &failedSensorReads, bool checkForNan=false)
bool readControlBoardInterface (bool checkForNan=false)
Read control board remapper interfaces.
bool readAllIMUs (std::vector< std::string > &failedSensorReads)
bool readAllCartesianWrenches (std::vector< std::string > &failedSensorReads)
bool readAllMASLinearAccelerometers (std::vector< std::string > &failedSensorReads)
bool readAllMASGyroscopes (std::vector< std::string > &failedSensorReads)
bool readAllMASOrientationSensors (std::vector< std::string > &failedSensorReads)
bool readAllMASMagnetometers (std::vector< std::string > &failedSensorReads)
bool readAllMASSixAxisForceTorqueSensors (std::vector< std::string > &failedSensorReads)
bool readAllSensors (std::vector< std::string > &failedReadAllSensors)
Data Fields
ControlBoardRemapperInterfaces controlBoardRemapperInterfaces
WholeBodyMASInertialsInterface wholeBodyMASInertialsInterface
WholeBodyMASForceTorquesInterface wholeBodyMASForceTorquesInterface
MASSensorIndexMaps masSensorIndexMaps
ControlBoardRemapperMeasures controlBoardRemapperMeasures
std::unordered_map< std::string, yarp::dev::IGenericSensor * > wholeBodyAnalogIMUInterface
std::unordered_map< std::string, yarp::dev::IGenericSensor * > wholeBodyCartesianWrenchInterface
< map of IMU sensors attached through generic sensor interfaces
std::unordered_map< std::string, yarp::dev::IAnalogSensor * > wholeBodyAnalogSixAxisFTSensorsInterface
< map of cartesian wrench streams attached through generic sensor interfaces
std::unordered_map< std::string, StampedYARPVector > wholeBodyIMUMeasures
< map of six axis force torque sensors attached through analog sensor interfaces
std::unordered_map< std::string, StampedYARPVector > wholeBodyFTMeasures
< map holding analog IMU sensor measurements
std::unordered_map< std::string, StampedYARPVector > wholeBodyInertialMeasures
< map holding six axis force torque measures
std::unordered_map< std::string, StampedYARPVector > wholeBodyCartesianWrenchMeasures
< map holding three axis inertial sensor measures
const int nrChannelsInYARPGenericIMUSensor {12}
< map holding cartesian wrench measures
const int nrChannelsInYARPGenericCartesianWrench {6}
const int nrChannelsInYARPAnalogSixAxisFTSensor {6}
std::vector< std::string > failedSensorReads
SensorBridgeMetaData metaData
struct holding meta data
bool bridgeInitialized {false}
flag set to true if the bridge is successfully initialized
bool driversAttached {false}
flag set to true if the bridge is successfully attached to required device drivers
bool checkForNAN {false}
flag to enable search for NANs in the incoming measurement buffers
Detailed Description
Definition at line 45 of file YarpSensorBridgeImpl.h.
Member Function Documentation
attachAllInertials()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachAllInertials (const yarp::dev::PolyDriverList & devList) inline
Attach generic IMU sensor types and MAS inertials.
Definition at line 735 of file YarpSensorBridgeImpl.h.
References attachAndCheckMASSensors(), BipedalLocomotion::RobotInterface::SensorLists::gyroscopesList, BipedalLocomotion::RobotInterface::SensorLists::IMUsList, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isGyroscopeEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isIMUEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isLinearAccelerometerEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isMagnetometerEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isOrientationSensorEnabled, BipedalLocomotion::RobotInterface::SensorLists::linearAccelerometersList, BipedalLocomotion::RobotInterface::SensorLists::magnetometersList, nrChannelsInYARPGenericIMUSensor, and BipedalLocomotion::RobotInterface::SensorLists::orientationSensorsList.
attachAndCheckMASSensors()
template<typename MASSensorType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachAndCheckMASSensors (const yarp::dev::PolyDriverList & devList, MASSensorType *& sensorInterface, const std::vector< std::string > & sensorList, const std::string_view interfaceName) inline
Attach Remapped Multiple Analog Sensor Interfaces and check available sensors.
Definition at line 423 of file YarpSensorBridgeImpl.h.
References attachRemappedMASSensor(), checkAttachedMASSensors(), and std::endl().
Referenced by attachAllInertials().
attachCartesianWrenchInterface()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachCartesianWrenchInterface (const yarp::dev::PolyDriverList & devList) inline
Attach to cartesian wrench interface.
Definition at line 974 of file YarpSensorBridgeImpl.h.
References BipedalLocomotion::RobotInterface::SensorLists::cartesianWrenchesList, and BipedalLocomotion::RobotInterface::SensorBridgeOptions::isCartesianWrenchEnabled.
attachGenericOrAnalogSensor()
template<typename SensorType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachGenericOrAnalogSensor (const yarp::dev::PolyDriverList & devList, const std::string & sensorName, const int & nrChannelsInSensor, std::unordered_map< std::string, SensorType *> & sensorMap) inline
Attach device with IGenericSensor or IAnalogSensor interfaces Important assumptions here,.
Any generic sensor with 12 channels is a IMU sensor
Any generic sensor with 6 channels is a cartesian wrench sensor
Any analog sensor with 6 channels is a six axis force torque sensor
Definition at line 338 of file YarpSensorBridgeImpl.h.
References std::endl(), and std::unordered_map< K, T >::size().
attachRemappedMASSensor()
template<typename MASSensorType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachRemappedMASSensor (const yarp::dev::PolyDriverList & devList, MASSensorType *& masSensorInterface) inline
Attach Remapped Multiple Analog Sensor Interfaces Looks for a specific MAS Sensor interface in the attached MAS Remapper.
Definition at line 451 of file YarpSensorBridgeImpl.h.
References std::endl().
Referenced by attachAndCheckMASSensors(), and compareControlBoardJointsList().
attachRemappedRemoteControlBoard()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::attachRemappedRemoteControlBoard (const yarp::dev::PolyDriverList & devList) inline
Attach a remapped control board and check the availability of desired interface Further, resize joint data buffers and check if the control board joints list and the desired joints list match Also, maintain a remapping index buffer for adapting to arbitrary joint list serializations.
Definition at line 801 of file YarpSensorBridgeImpl.h.
References compareControlBoardJointsList(), std::endl(), and BipedalLocomotion::RobotInterface::SensorBridgeOptions::isKinematicsEnabled.
checkAttachedMASSensors()
template<typename MASSensorType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkAttachedMASSensors (const yarp::dev::PolyDriverList & devList, MASSensorType *& sensorInterface, const std::vector< std::string > & sensorList) inline
Check if all the desired MAS sensors are availabled in the attached MAS interface.
Definition at line 483 of file YarpSensorBridgeImpl.h.
References std::endl(), getMASSensorName(), getNumberOfMASSensors(), and std::vector< T >::size().
Referenced by attachAndCheckMASSensors().
checkSensor()
template<typename SensorType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkSensor (const std::unordered_map< std::string, SensorType * > & sensorMap, const std::string & sensorName) inline
Check if sensor is available in the relevant sensor map.
Definition at line 686 of file YarpSensorBridgeImpl.h.
References std::unordered_map< K, T >::end(), and std::unordered_map< K, T >::find().
Referenced by readAnalogOrGenericSensor().
checkValid()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkValid (const std::string_view methodName) inline
Check if the bridge is successfully initialized and attached to required device drivers.
Definition at line 722 of file YarpSensorBridgeImpl.h.
References bridgeInitialized, and driversAttached.
Referenced by checkValidSensorMeasure().
checkValidSensorMeasure()
template<typename YARPDataType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkValidSensorMeasure (std::string_view logPrefix, const std::unordered_map< std::string, YARPDataType > & sensorMap, const std::string & sensorName) inline
Check if sensor is available in the relevant sensor measurement map.
Definition at line 701 of file YarpSensorBridgeImpl.h.
References checkValid(), std::unordered_map< K, T >::end(), std::endl(), and std::unordered_map< K, T >::find().
compareControlBoardJointsList()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::compareControlBoardJointsList () inline
check and match control board joints with the sensorbridge joints list
Definition at line 860 of file YarpSensorBridgeImpl.h.
References attachRemappedMASSensor(), std::back_inserter(), std::vector< T >::begin(), std::distance(), std::vector< T >::empty(), std::vector< T >::end(), std::endl(), std::find_if(), getAllSensorsInMASInterface(), BipedalLocomotion::RobotInterface::SensorBridgeOptions::isSixAxisForceTorqueSensorEnabled, BipedalLocomotion::RobotInterface::SensorLists::jointsList, BipedalLocomotion::RobotInterface::SensorBridgeOptions::nrJoints, std::vector< T >::push_back(), resetControlBoardBuffers(), std::set_intersection(), BipedalLocomotion::RobotInterface::SensorLists::sixAxisForceTorqueSensorsList, std::vector< T >::size(), and std::sort().
Referenced by attachRemappedRemoteControlBoard().
configureCartesianWrenches()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureCartesianWrenches (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData & metaData) inline
Configure cartesian wrenches meta data.
Definition at line 310 of file YarpSensorBridgeImpl.h.
References BipedalLocomotion::RobotInterface::SensorLists::cartesianWrenchesList, std::endl(), and std::weak_ptr< T >::lock().
Referenced by BipedalLocomotion::RobotInterface::YarpSensorBridge::initialize().
configureInertialSensors()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureInertialSensors (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData & metaData) inline
Configure inertial sensors meta data.
Definition at line 249 of file YarpSensorBridgeImpl.h.
References BipedalLocomotion::RobotInterface::SensorLists::gyroscopesList, BipedalLocomotion::RobotInterface::SensorLists::IMUsList, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isGyroscopeEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isIMUEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isLinearAccelerometerEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isMagnetometerEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isOrientationSensorEnabled, BipedalLocomotion::RobotInterface::SensorLists::linearAccelerometersList, std::weak_ptr< T >::lock(), BipedalLocomotion::RobotInterface::SensorLists::magnetometersList, and BipedalLocomotion::RobotInterface::SensorLists::orientationSensorsList.
Referenced by BipedalLocomotion::RobotInterface::YarpSensorBridge::initialize().
configureRemoteControlBoardRemapper()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureRemoteControlBoardRemapper (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData & metaData) inline
Configure remote control board remapper meta data Related to kinematics and other joint/motor relevant quantities.
Definition at line 211 of file YarpSensorBridgeImpl.h.
References std::vector< T >::clear(), std::endl(), BipedalLocomotion::RobotInterface::SensorLists::jointsList, std::weak_ptr< T >::lock(), BipedalLocomotion::RobotInterface::SensorBridgeOptions::nrJoints, and std::vector< T >::size().
Referenced by BipedalLocomotion::RobotInterface::YarpSensorBridge::initialize().
configureSixAxisForceTorqueSensors()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::configureSixAxisForceTorqueSensors (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData & metaData) inline
Configure six axis force torque sensors meta data.
Definition at line 287 of file YarpSensorBridgeImpl.h.
References std::endl(), std::weak_ptr< T >::lock(), and BipedalLocomotion::RobotInterface::SensorLists::sixAxisForceTorqueSensorsList.
Referenced by BipedalLocomotion::RobotInterface::YarpSensorBridge::initialize().
deg2rad()
double BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::deg2rad (double deg) inline
utility function
Definition at line 1002 of file YarpSensorBridgeImpl.h.
Referenced by readAnalogOrGenericSensor(), and readControlBoardInterface().
getAllSensorsInMASInterface()
template<typename MASSensorType > std::vector<std::string> BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::getAllSensorsInMASInterface (MASSensorType * sensorInterface) inline
Get all sensor names in a MAS Inerface.
Definition at line 620 of file YarpSensorBridgeImpl.h.
References std::vector< T >::push_back().
Referenced by compareControlBoardJointsList().
getIndexFromVector()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::getIndexFromVector (const std::vector< std::string > & vec, const std::string & query, int & index) inline
Utility function to get index from vector.
Definition at line 136 of file YarpSensorBridgeImpl.h.
References std::vector< T >::begin(), std::vector< T >::end(), and std::lower_bound().
getMASSensorName()
template<typename MASSensorType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::getMASSensorName (MASSensorType *& sensorInterface, const std::size_t & sensIdx, std::string & sensorName) inline
Get name of MAS Sensors.
Definition at line 584 of file YarpSensorBridgeImpl.h.
Referenced by checkAttachedMASSensors().
getNumberOfMASSensors()
template<typename MASSensorType > std::size_t BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::getNumberOfMASSensors (MASSensorType *& sensorInterface) inline
Get number of MAS Sensors.
Definition at line 549 of file YarpSensorBridgeImpl.h.
Referenced by checkAttachedMASSensors().
nanExistsInVec()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::nanExistsInVec (const yarp::sig::Vector & vec, std::string_view logPrefix, const std::string & sensorName) inline
Utility function to check for nan in vector.
Definition at line 153 of file YarpSensorBridgeImpl.h.
References std::endl(), and std::isnan().
Referenced by readAnalogOrGenericSensor(), and readControlBoardInterface().
readAnalogOrGenericSensor()
template<typename SensorType > bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::readAnalogOrGenericSensor (const std::string & sensorName, const int & nrChannelsInYARPSensor, std::unordered_map< std::string, SensorType * > & interfaceMap, std::unordered_map< std::string, StampedYARPVector > & measurementMap, bool checkForNan = false) inline
Read generic or analog sensor stream and update internal measurement buffer.
Definition at line 1011 of file YarpSensorBridgeImpl.h.
References checkSensor(), std::vector< T >::clear(), deg2rad(), std::vector< T >::emplace_back(), std::unordered_map< K, T >::end(), std::endl(), std::unordered_map< K, T >::find(), nanExistsInVec(), and nrChannelsInYARPGenericIMUSensor.
Referenced by readControlBoardInterface().
readControlBoardInterface()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::readControlBoardInterface (bool checkForNan = false) inline
Read control board remapper interfaces.
Definition at line 1189 of file YarpSensorBridgeImpl.h.
References std::vector< T >::begin(), checkForNAN, std::vector< T >::clear(), deg2rad(), std::vector< T >::emplace_back(), std::vector< T >::end(), std::endl(), std::vector< T >::insert(), BipedalLocomotion::RobotInterface::SensorBridgeOptions::isCartesianWrenchEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isGyroscopeEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isIMUEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isKinematicsEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isLinearAccelerometerEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isMagnetometerEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isOrientationSensorEnabled, BipedalLocomotion::RobotInterface::SensorBridgeOptions::isSixAxisForceTorqueSensorEnabled, nanExistsInVec(), nrChannelsInYARPGenericIMUSensor, and readAnalogOrGenericSensor().
resetControlBoardBuffers()
void BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::resetControlBoardBuffers () inline
resize and set control board buffers to zero
Definition at line 842 of file YarpSensorBridgeImpl.h.
References BipedalLocomotion::RobotInterface::SensorBridgeOptions::nrJoints.
Referenced by compareControlBoardJointsList().
subConfigLoader()
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::subConfigLoader (const std::string & enableStreamString, const std::string & streamGroupString, const SubConfigLoader loader, std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler, SensorBridgeMetaData & metaData, bool & enableStreamFlag) inline
Checks is a stream is enabled in configuration and loads the relevant stream group from configuration.
Definition at line 172 of file YarpSensorBridgeImpl.h.
References std::endl(), and std::weak_ptr< T >::lock().
Field Documentation
bridgeInitialized
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::bridgeInitialized {false}
flag set to true if the bridge is successfully initialized
Definition at line 126 of file YarpSensorBridgeImpl.h.
Referenced by checkValid().
checkForNAN
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::checkForNAN {false}
flag to enable search for NANs in the incoming measurement buffers
Definition at line 128 of file YarpSensorBridgeImpl.h.
Referenced by readControlBoardInterface().
driversAttached
bool BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::driversAttached {false}
flag set to true if the bridge is successfully attached to required device drivers
Definition at line 127 of file YarpSensorBridgeImpl.h.
Referenced by checkValid().
metaData
SensorBridgeMetaData BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::metaData
struct holding meta data
Definition at line 125 of file YarpSensorBridgeImpl.h.
nrChannelsInYARPGenericIMUSensor
const int BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::nrChannelsInYARPGenericIMUSensor {12}
< map holding cartesian wrench measures
Definition at line 120 of file YarpSensorBridgeImpl.h.
Referenced by attachAllInertials(), readAnalogOrGenericSensor(), and readControlBoardInterface().
wholeBodyAnalogSixAxisFTSensorsInterface
std::unordered_map<std::string, yarp::dev::IAnalogSensor*> BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::wholeBodyAnalogSixAxisFTSensorsInterface
< map of cartesian wrench streams attached through generic sensor interfaces
Definition at line 113 of file YarpSensorBridgeImpl.h.
wholeBodyCartesianWrenchInterface
std::unordered_map<std::string, yarp::dev::IGenericSensor*> BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::wholeBodyCartesianWrenchInterface
< map of IMU sensors attached through generic sensor interfaces
Definition at line 112 of file YarpSensorBridgeImpl.h.
wholeBodyCartesianWrenchMeasures
std::unordered_map<std::string, StampedYARPVector> BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::wholeBodyCartesianWrenchMeasures
< map holding three axis inertial sensor measures
Definition at line 118 of file YarpSensorBridgeImpl.h.
wholeBodyFTMeasures
std::unordered_map<std::string, StampedYARPVector> BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::wholeBodyFTMeasures
< map holding analog IMU sensor measurements
Definition at line 116 of file YarpSensorBridgeImpl.h.
wholeBodyIMUMeasures
std::unordered_map<std::string, StampedYARPVector> BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::wholeBodyIMUMeasures
< map of six axis force torque sensors attached through analog sensor interfaces
Definition at line 115 of file YarpSensorBridgeImpl.h.
wholeBodyInertialMeasures
std::unordered_map<std::string, StampedYARPVector> BipedalLocomotion::RobotInterface::YarpSensorBridge::Impl::wholeBodyInertialMeasures
< map holding six axis force torque measures
Definition at line 117 of file YarpSensorBridgeImpl.h.
The documentation for this struct was generated from the following file:
RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpSensorBridgeImpl.h