bipedal-locomotion-framework: RobotInterface/YarpImplementation/include/BipedalLocomotion/RobotInterface/YarpHelper.h File Reference
YarpHelper.h File Reference
#include <memory>
#include <string>
#include <yarp/dev/PolyDriver.h>
#include <BipedalLocomotion/ParametersHandler/IParametersHandler.h>
Data Structures
struct BipedalLocomotion::RobotInterface::PolyDriverDescriptor
PolyDriverDescriptor describes a PolyDriver.
Functions
PolyDriverDescriptor BipedalLocomotion::RobotInterface::constructRemoteControlBoardRemapper (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a RemoteControlBoardRemapper device.
PolyDriverDescriptor BipedalLocomotion::RobotInterface::constructGenericSensorClient (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a GenericSensorClient device.
Detailed Description
Authors
Giulio Romualdi
Copyright
2020 Istituto Italiano di Tecnologia (IIT). This software may be modified and distributed under the terms of the GNU Lesser General Public License v2.1 or any later version.
Definition in file YarpHelper.h.
Function Documentation
constructGenericSensorClient()
PolyDriverDescriptor BipedalLocomotion::RobotInterface::constructGenericSensorClient (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a GenericSensorClient device.
Parameters
handler pointer to a parameter handler interface.
Note
the following parameters are required by the function
Parameter Name Type Description Mandatory
description string Description of the genericSensorClient. It is the device name Yes
remote_port_name string Name of the port associate to the remote Yes
local_prefix string Prefix of the local port (e.g. the application name) Yes
local_port_name_suffix string Suffix of the local port. The local port name is /<local_prefix><local_port_name_suffix> Yes
The genericSensorClient device is implement in whole-body-estimators.
Returns
A PolyDriverDescriptor. If one of the parameters is missing an invalid PolyDriverDescriptor is returned.
Definition at line 92 of file YarpHelper.cpp.
References BipedalLocomotion::RobotInterface::constructGenericSensorClient(), std::endl(), std::weak_ptr< T >::lock(), BipedalLocomotion::RobotInterface::PolyDriverDescriptor::poly, and BipedalLocomotion::RobotInterface::PolyDriverDescriptor::PolyDriverDescriptor().
Referenced by BipedalLocomotion::RobotInterface::constructGenericSensorClient().
constructRemoteControlBoardRemapper()
PolyDriverDescriptor BipedalLocomotion::RobotInterface::constructRemoteControlBoardRemapper (std::weak_ptr< BipedalLocomotion::ParametersHandler::IParametersHandler > handler)
Helper function that can be used to build a RemoteControlBoardRemapper device.
Parameters
handler pointer to a parameter handler interface.
Note
the following parameters are required by the function
Parameter Name Type Description Mandatory
joints_list vector<string> List of the controlled joints Yes
remote_control_boards vector<string> List of the remote control boards associated to the joints Yes
robot_name string Name of the robot Yes
local_prefix string Prefix of the local port (e.g. the application name) Yes
Returns
A PolyDriverDescriptor. If one of the parameters is missing an invalid PolyDriverDescriptor is returned.
Definition at line 26 of file YarpHelper.cpp.
References BipedalLocomotion::RobotInterface::constructRemoteControlBoardRemapper(), std::endl(), std::weak_ptr< T >::lock(), BipedalLocomotion::RobotInterface::PolyDriverDescriptor::poly, and BipedalLocomotion::RobotInterface::PolyDriverDescriptor::PolyDriverDescriptor().
Referenced by BipedalLocomotion::RobotInterface::constructRemoteControlBoardRemapper().